import { CountryLanguage } from './i18n';

export const COMPREHENSIVE_WORLD_LANGUAGES: CountryLanguage[] = [
  // ==========================================
  // TOP GLOBAL STANDARDS
  // ==========================================
  { code: 'en-US', name: 'English (United States)', nativeName: 'English (US)', flag: '🇺🇸', region: 'Americas' },
  { code: 'en-GB', name: 'English (United Kingdom)', nativeName: 'English (UK)', flag: '🇬🇧', region: 'Europe' },
  { code: 'en-CA', name: 'English (Canada)', nativeName: 'English (CA)', flag: '🇨🇦', region: 'Americas' },
  { code: 'en-AU', name: 'English (Australia)', nativeName: 'English (AU)', flag: '🇦🇺', region: 'Oceania' },
  { code: 'en-NZ', name: 'English (New Zealand)', nativeName: 'English (NZ)', flag: '🇳🇿', region: 'Oceania' },
  { code: 'en-IE', name: 'English (Ireland)', nativeName: 'English (IE)', flag: '🇮🇪', region: 'Europe' },
  { code: 'en-ZA', name: 'English (South Africa)', nativeName: 'English (ZA)', flag: '🇿🇦', region: 'Africa' },
  { code: 'en-IN', name: 'English (India)', nativeName: 'English (India)', flag: '🇮🇳', region: 'Asia' },
  { code: 'en-SG', name: 'English (Singapore)', nativeName: 'English (SG)', flag: '🇸🇬', region: 'Asia' },
  { code: 'en-NG', name: 'English (Nigeria)', nativeName: 'English (NG)', flag: '🇳🇬', region: 'Africa' },
  { code: 'en-KE', name: 'English (Kenya)', nativeName: 'English (KE)', flag: '🇰🇪', region: 'Africa' },
  { code: 'en-GH', name: 'English (Ghana)', nativeName: 'English (GH)', flag: '🇬🇭', region: 'Africa' },
  { code: 'en-PH', name: 'English (Philippines)', nativeName: 'English (PH)', flag: '🇵🇭', region: 'Asia' },
  { code: 'en-JM', name: 'English (Jamaica)', nativeName: 'English (JM)', flag: '🇯🇲', region: 'Caribbean' },
  { code: 'en-TT', name: 'English (Trinidad & Tobago)', nativeName: 'English (TT)', flag: '🇹🇹', region: 'Caribbean' },
  { code: 'en-BZ', name: 'English (Belize)', nativeName: 'English (BZ)', flag: '🇧🇿', region: 'Americas' },
  { code: 'en-GY', name: 'English (Guyana)', nativeName: 'English (GY)', flag: '🇬🇾', region: 'Americas' },
  { code: 'en-BS', name: 'English (Bahamas)', nativeName: 'English (BS)', flag: '🇧🇸', region: 'Caribbean' },
  { code: 'en-BB', name: 'English (Barbados)', nativeName: 'English (BB)', flag: '🇧🇧', region: 'Caribbean' },
  { code: 'en-MT', name: 'English (Malta)', nativeName: 'English (MT)', flag: '🇲🇹', region: 'Europe' },

  // ==========================================
  // SPANISH DIALECTS (ESPAÑOL)
  // ==========================================
  { code: 'es-ES', name: 'Spanish (Spain)', nativeName: 'Español (España)', flag: '🇪🇸', region: 'Europe' },
  { code: 'es-MX', name: 'Spanish (Mexico)', nativeName: 'Español (México)', flag: '🇲🇽', region: 'Americas' },
  { code: 'es-AR', name: 'Spanish (Argentina)', nativeName: 'Español (Argentina)', flag: '🇦🇷', region: 'Americas' },
  { code: 'es-CO', name: 'Spanish (Colombia)', nativeName: 'Español (Colombia)', flag: '🇨🇴', region: 'Americas' },
  { code: 'es-CL', name: 'Spanish (Chile)', nativeName: 'Español (Chile)', flag: '🇨🇱', region: 'Americas' },
  { code: 'es-PE', name: 'Spanish (Peru)', nativeName: 'Español (Perú)', flag: '🇵🇪', region: 'Americas' },
  { code: 'es-VE', name: 'Spanish (Venezuela)', nativeName: 'Español (Venezuela)', flag: '🇻🇪', region: 'Americas' },
  { code: 'es-EC', name: 'Spanish (Ecuador)', nativeName: 'Español (Ecuador)', flag: '🇪🇨', region: 'Americas' },
  { code: 'es-GT', name: 'Spanish (Guatemala)', nativeName: 'Español (Guatemala)', flag: '🇬🇹', region: 'Americas' },
  { code: 'es-CU', name: 'Spanish (Cuba)', nativeName: 'Español (Cuba)', flag: '🇨🇺', region: 'Caribbean' },
  { code: 'es-DO', name: 'Spanish (Dominican Republic)', nativeName: 'Español (Rep. Dominicana)', flag: '🇩🇴', region: 'Caribbean' },
  { code: 'es-BO', name: 'Spanish (Bolivia)', nativeName: 'Español (Bolivia)', flag: '🇧🇴', region: 'Americas' },
  { code: 'es-HN', name: 'Spanish (Honduras)', nativeName: 'Español (Honduras)', flag: '🇭🇳', region: 'Americas' },
  { code: 'es-PY', name: 'Spanish (Paraguay)', nativeName: 'Español (Paraguay)', flag: '🇵🇾', region: 'Americas' },
  { code: 'es-SV', name: 'Spanish (El Salvador)', nativeName: 'Español (El Salvador)', flag: '🇸🇻', region: 'Americas' },
  { code: 'es-NI', name: 'Spanish (Nicaragua)', nativeName: 'Español (Nicaragua)', flag: '🇳🇮', region: 'Americas' },
  { code: 'es-CR', name: 'Spanish (Costa Rica)', nativeName: 'Español (Costa Rica)', flag: '🇨🇷', region: 'Americas' },
  { code: 'es-PR', name: 'Spanish (Puerto Rico)', nativeName: 'Español (Puerto Rico)', flag: '🇵🇷', region: 'Caribbean' },
  { code: 'es-PA', name: 'Spanish (Panama)', nativeName: 'Español (Panamá)', flag: '🇵🇦', region: 'Americas' },
  { code: 'es-UY', name: 'Spanish (Uruguay)', nativeName: 'Español (Uruguay)', flag: '🇺🇾', region: 'Americas' },
  { code: 'es-GQ', name: 'Spanish (Equatorial Guinea)', nativeName: 'Español (Guinea Ecuatorial)', flag: '🇬🇶', region: 'Africa' },

  // ==========================================
  // FRENCH DIALECTS (FRANÇAIS)
  // ==========================================
  { code: 'fr-FR', name: 'French (France)', nativeName: 'Français (France)', flag: '🇫🇷', region: 'Europe' },
  { code: 'fr-CA', name: 'French (Canada / Québec)', nativeName: 'Français (Canada)', flag: '🇨🇦', region: 'Americas' },
  { code: 'fr-BE', name: 'French (Belgium)', nativeName: 'Français (Belgique)', flag: '🇧🇪', region: 'Europe' },
  { code: 'fr-CH', name: 'French (Switzerland)', nativeName: 'Français (Suisse)', flag: '🇨🇭', region: 'Europe' },
  { code: 'fr-SN', name: 'French (Senegal)', nativeName: 'Français (Sénégal)', flag: '🇸🇳', region: 'Africa' },
  { code: 'fr-CI', name: 'French (Côte d’Ivoire)', nativeName: 'Français (Côte d’Ivoire)', flag: '🇨🇮', region: 'Africa' },
  { code: 'fr-CD', name: 'French (DR Congo)', nativeName: 'Français (RD Congo)', flag: '🇨🇩', region: 'Africa' },
  { code: 'fr-CM', name: 'French (Cameroon)', nativeName: 'Français (Cameroun)', flag: '🇨🇲', region: 'Africa' },
  { code: 'fr-MG', name: 'French (Madagascar)', nativeName: 'Français (Madagascar)', flag: '🇲🇬', region: 'Africa' },
  { code: 'fr-ML', name: 'French (Mali)', nativeName: 'Français (Mali)', flag: '🇲🇱', region: 'Africa' },
  { code: 'fr-BF', name: 'French (Burkina Faso)', nativeName: 'Français (Burkina Faso)', flag: '🇧🇫', region: 'Africa' },
  { code: 'fr-NE', name: 'French (Niger)', nativeName: 'Français (Niger)', flag: '🇳🇪', region: 'Africa' },
  { code: 'fr-GN', name: 'French (Guinea)', nativeName: 'Français (Guinée)', flag: '🇬🇳', region: 'Africa' },
  { code: 'fr-RW', name: 'French (Rwanda)', nativeName: 'Français (Rwanda)', flag: '🇷🇼', region: 'Africa' },
  { code: 'fr-HT', name: 'French (Haiti)', nativeName: 'Français (Haïti)', flag: '🇭🇹', region: 'Caribbean' },
  { code: 'fr-LU', name: 'French (Luxembourg)', nativeName: 'Français (Luxembourg)', flag: '🇱🇺', region: 'Europe' },
  { code: 'fr-MC', name: 'French (Monaco)', nativeName: 'Français (Monaco)', flag: '🇲🇨', region: 'Europe' },
  { code: 'fr-TG', name: 'French (Togo)', nativeName: 'Français (Togo)', flag: '🇹🇬', region: 'Africa' },
  { code: 'fr-BJ', name: 'French (Benin)', nativeName: 'Français (Bénin)', flag: '🇧🇯', region: 'Africa' },
  { code: 'fr-GA', name: 'French (Gabon)', nativeName: 'Français (Gabon)', flag: '🇬🇦', region: 'Africa' },

  // ==========================================
  // ARABIC DIALECTS (العربية)
  // ==========================================
  { code: 'ar-SA', name: 'Arabic (Saudi Arabia)', nativeName: 'العربية (السعودية)', flag: '🇸🇦', region: 'Middle East', rtl: true },
  { code: 'ar-EG', name: 'Arabic (Egypt)', nativeName: 'العربية (مصر)', flag: '🇪🇬', region: 'Africa / Middle East', rtl: true },
  { code: 'ar-AE', name: 'Arabic (United Arab Emirates)', nativeName: 'العربية (الإمارات)', flag: '🇦🇪', region: 'Middle East', rtl: true },
  { code: 'ar-DZ', name: 'Arabic (Algeria)', nativeName: 'العربية (الجزائر)', flag: '🇩🇿', region: 'North Africa', rtl: true },
  { code: 'ar-MA', name: 'Arabic (Morocco)', nativeName: 'العربية (المغرب)', flag: '🇲🇦', region: 'North Africa', rtl: true },
  { code: 'ar-IQ', name: 'Arabic (Iraq)', nativeName: 'العربية (العراق)', flag: '🇮🇶', region: 'Middle East', rtl: true },
  { code: 'ar-SD', name: 'Arabic (Sudan)', nativeName: 'العربية (السودان)', flag: '🇸🇩', region: 'Africa', rtl: true },
  { code: 'ar-YE', name: 'Arabic (Yemen)', nativeName: 'العربية (اليمن)', flag: '🇾🇪', region: 'Middle East', rtl: true },
  { code: 'ar-SY', name: 'Arabic (Syria)', nativeName: 'العربية (سوريا)', flag: '🇸🇾', region: 'Middle East', rtl: true },
  { code: 'ar-TN', name: 'Arabic (Tunisia)', nativeName: 'العربية (تونس)', flag: '🇹🇳', region: 'North Africa', rtl: true },
  { code: 'ar-JO', name: 'Arabic (Jordan)', nativeName: 'العربية (الأردن)', flag: '🇯🇴', region: 'Middle East', rtl: true },
  { code: 'ar-LB', name: 'Arabic (Lebanon)', nativeName: 'العربية (لبنان)', flag: '🇱🇧', region: 'Middle East', rtl: true },
  { code: 'ar-LY', name: 'Arabic (Libya)', nativeName: 'العربية (ليبيا)', flag: '🇱🇾', region: 'North Africa', rtl: true },
  { code: 'ar-PS', name: 'Arabic (Palestine)', nativeName: 'العربية (فلسطين)', flag: '🇵🇸', region: 'Middle East', rtl: true },
  { code: 'ar-OM', name: 'Arabic (Oman)', nativeName: 'العربية (عُمان)', flag: '🇴🇲', region: 'Middle East', rtl: true },
  { code: 'ar-KW', name: 'Arabic (Kuwait)', nativeName: 'العربية (الكويت)', flag: '🇰🇼', region: 'Middle East', rtl: true },
  { code: 'ar-QA', name: 'Arabic (Qatar)', nativeName: 'العربية (قطر)', flag: '🇶🇦', region: 'Middle East', rtl: true },
  { code: 'ar-BH', name: 'Arabic (Bahrain)', nativeName: 'العربية (البحرين)', flag: '🇧🇭', region: 'Middle East', rtl: true },
  { code: 'ar-MR', name: 'Arabic (Mauritania)', nativeName: 'العربية (موريتانيا)', flag: '🇲🇷', region: 'Africa', rtl: true },
  { code: 'ar-SO', name: 'Arabic (Somalia)', nativeName: 'العربية (الصومال)', flag: '🇸🇴', region: 'Africa', rtl: true },

  // ==========================================
  // PORTUGUESE (PORTUGUÊS)
  // ==========================================
  { code: 'pt-BR', name: 'Portuguese (Brazil)', nativeName: 'Português (Brasil)', flag: '🇧🇷', region: 'Americas' },
  { code: 'pt-PT', name: 'Portuguese (Portugal)', nativeName: 'Português (Portugal)', flag: '🇵🇹', region: 'Europe' },
  { code: 'pt-AO', name: 'Portuguese (Angola)', nativeName: 'Português (Angola)', flag: '🇦🇴', region: 'Africa' },
  { code: 'pt-MZ', name: 'Portuguese (Mozambique)', nativeName: 'Português (Moçambique)', flag: '🇲🇿', region: 'Africa' },
  { code: 'pt-CV', name: 'Portuguese (Cape Verde)', nativeName: 'Português (Cabo Verde)', flag: '🇨🇻', region: 'Africa' },
  { code: 'pt-GW', name: 'Portuguese (Guinea-Bissau)', nativeName: 'Português (Guiné-Bissau)', flag: '🇬🇼', region: 'Africa' },
  { code: 'pt-ST', name: 'Portuguese (São Tomé & Príncipe)', nativeName: 'Português (São Tomé)', flag: '🇸🇹', region: 'Africa' },
  { code: 'pt-TL', name: 'Portuguese (Timor-Leste)', nativeName: 'Português (Timor-Leste)', flag: '🇹🇱', region: 'Asia' },
  { code: 'pt-MO', name: 'Portuguese (Macau)', nativeName: 'Português (Macau)', flag: '🇲🇴', region: 'Asia' },

  // ==========================================
  // GERMAN (DEUTSCH)
  // ==========================================
  { code: 'de-DE', name: 'German (Germany)', nativeName: 'Deutsch (Deutschland)', flag: '🇩🇪', region: 'Europe' },
  { code: 'de-AT', name: 'German (Austria)', nativeName: 'Deutsch (Österreich)', flag: '🇦🇹', region: 'Europe' },
  { code: 'de-CH', name: 'German (Switzerland)', nativeName: 'Deutsch (Schweiz)', flag: '🇨🇭', region: 'Europe' },
  { code: 'de-LI', name: 'German (Liechtenstein)', nativeName: 'Deutsch (Liechtenstein)', flag: '🇱🇮', region: 'Europe' },
  { code: 'de-LU', name: 'German (Luxembourg)', nativeName: 'Deutsch (Luxemburg)', flag: '🇱🇺', region: 'Europe' },
  { code: 'de-BE', name: 'German (Belgium)', nativeName: 'Deutsch (Belgien)', flag: '🇧🇪', region: 'Europe' },

  // ==========================================
  // CHINESE (中文 VARIETIES)
  // ==========================================
  { code: 'zh-CN', name: 'Chinese (Simplified Mandarin - China)', nativeName: '简体中文 (中国大陆)', flag: '🇨🇳', region: 'Asia' },
  { code: 'zh-TW', name: 'Chinese (Traditional Mandarin - Taiwan)', nativeName: '繁體中文 (台灣)', flag: '🇹🇼', region: 'Asia' },
  { code: 'zh-HK', name: 'Chinese (Cantonese / Traditional - Hong Kong)', nativeName: '繁體中文 (香港)', flag: '🇭🇰', region: 'Asia' },
  { code: 'zh-MO', name: 'Chinese (Traditional - Macau)', nativeName: '繁體中文 (澳門)', flag: '🇲🇴', region: 'Asia' },
  { code: 'zh-SG', name: 'Chinese (Simplified - Singapore)', nativeName: '简体中文 (新加坡)', flag: '🇸🇬', region: 'Asia' },
  { code: 'zh-MY', name: 'Chinese (Simplified - Malaysia)', nativeName: '简体中文 (马来西亚)', flag: '🇲🇾', region: 'Asia' },
  { code: 'yue', name: 'Cantonese (Yue Chinese)', nativeName: '粵語 / 廣東話', flag: '🇭🇰', region: 'Asia' },
  { code: 'wuu', name: 'Shanghainese (Wu Chinese)', nativeName: '吳語 / 上海話', flag: '🇨🇳', region: 'Asia' },
  { code: 'nan', name: 'Hokkien / Taiwanese (Min Nan)', nativeName: '閩南語 / 臺灣話', flag: '🇹🇼', region: 'Asia' },
  { code: 'hak', name: 'Hakka Chinese', nativeName: '客家話', flag: '🇨🇳', region: 'Asia' },
  { code: 'hsn', name: 'Xiang Chinese (Hunanese)', nativeName: '湘語', flag: '🇨🇳', region: 'Asia' },
  { code: 'gan', name: 'Gan Chinese (Jiangxinese)', nativeName: '贛語', flag: '🇨🇳', region: 'Asia' },

  // ==========================================
  // INDIAN SUBCONTINENT LANGUAGES (BHARAT)
  // ==========================================
  { code: 'hi-IN', name: 'Hindi (India)', nativeName: 'हिन्दी', flag: '🇮🇳', region: 'Asia' },
  { code: 'bn-BD', name: 'Bengali (Bangladesh)', nativeName: 'বাংলা (বাংলাদেশ)', flag: '🇧🇩', region: 'Asia' },
  { code: 'bn-IN', name: 'Bengali (India)', nativeName: 'বাংলা (ভারত)', flag: '🇮🇳', region: 'Asia' },
  { code: 'te-IN', name: 'Telugu (India)', nativeName: 'తెలుగు', flag: '🇮🇳', region: 'Asia' },
  { code: 'mr-IN', name: 'Marathi (India)', nativeName: 'मराठी', flag: '🇮🇳', region: 'Asia' },
  { code: 'ta-IN', name: 'Tamil (India)', nativeName: 'தமிழ் (இந்தியா)', flag: '🇮🇳', region: 'Asia' },
  { code: 'ta-LK', name: 'Tamil (Sri Lanka)', nativeName: 'தமிழ் (இலங்கை)', flag: '🇱🇰', region: 'Asia' },
  { code: 'ta-SG', name: 'Tamil (Singapore)', nativeName: 'தமிழ் (சிங்கப்பூர்)', flag: '🇸🇬', region: 'Asia' },
  { code: 'ta-MY', name: 'Tamil (Malaysia)', nativeName: 'தமிழ் (மலேசியா)', flag: '🇲🇾', region: 'Asia' },
  { code: 'ur-PK', name: 'Urdu (Pakistan)', nativeName: 'اردو (پاکستان)', flag: '🇵🇰', region: 'Asia', rtl: true },
  { code: 'ur-IN', name: 'Urdu (India)', nativeName: 'اردو (بھارت)', flag: '🇮🇳', region: 'Asia', rtl: true },
  { code: 'gu-IN', name: 'Gujarati (India)', nativeName: 'ગુજરાતી', flag: '🇮🇳', region: 'Asia' },
  { code: 'kn-IN', name: 'Kannada (India)', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳', region: 'Asia' },
  { code: 'ml-IN', name: 'Malayalam (India)', nativeName: 'മലയാളം', flag: '🇮🇳', region: 'Asia' },
  { code: 'or-IN', name: 'Odia (India)', nativeName: 'ଓଡ଼ିଆ', flag: '🇮🇳', region: 'Asia' },
  { code: 'pa-IN', name: 'Punjabi (Gurmukhi - India)', nativeName: 'ਪੰਜਾਬੀ (ਭਾਰਤ)', flag: '🇮🇳', region: 'Asia' },
  { code: 'pa-PK', name: 'Punjabi (Shahmukhi - Pakistan)', nativeName: 'پنجابی (پاکستان)', flag: '🇵🇰', region: 'Asia', rtl: true },
  { code: 'as-IN', name: 'Assamese (India)', nativeName: 'অসমীয়া', flag: '🇮🇳', region: 'Asia' },
  { code: 'mai-IN', name: 'Maithili (India)', nativeName: 'मैथिली', flag: '🇮🇳', region: 'Asia' },
  { code: 'bho-IN', name: 'Bhojpuri (India)', nativeName: 'भोजपुरी', flag: '🇮🇳', region: 'Asia' },
  { code: 'sa-IN', name: 'Sanskrit (India)', nativeName: 'संस्कृतम्', flag: '🇮🇳', region: 'Asia' },
  { code: 'ne-NP', name: 'Nepali (Nepal)', nativeName: 'नेपाली (नेपाल)', flag: '🇳🇵', region: 'Asia' },
  { code: 'ne-IN', name: 'Nepali (India)', nativeName: 'नेपाली (भारत)', flag: '🇮🇳', region: 'Asia' },
  { code: 'sd-PK', name: 'Sindhi (Pakistan)', nativeName: 'سنڌي', flag: '🇵🇰', region: 'Asia', rtl: true },
  { code: 'sd-IN', name: 'Sindhi (Devanagari - India)', nativeName: 'सिन्धी', flag: '🇮🇳', region: 'Asia' },
  { code: 'kok-IN', name: 'Konkani (India)', nativeName: 'कोंकणी', flag: '🇮🇳', region: 'Asia' },
  { code: 'doi-IN', name: 'Dogri (India)', nativeName: 'डोगरी', flag: '🇮🇳', region: 'Asia' },
  { code: 'mni-IN', name: 'Manipuri / Meitei (India)', nativeName: 'মৈতৈলোন্', flag: '🇮🇳', region: 'Asia' },
  { code: 'sat-IN', name: 'Santali (Ol Chiki - India)', nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ', flag: '🇮🇳', region: 'Asia' },
  { code: 'brx-IN', name: 'Bodo (India)', nativeName: 'बड़ो', flag: '🇮🇳', region: 'Asia' },
  { code: 'ks-IN', name: 'Kashmiri (India)', nativeName: 'कॉशुर / كٲشُر', flag: '🇮🇳', region: 'Asia', rtl: true },
  { code: 'mwr-IN', name: 'Marwari (India)', nativeName: 'मारवाड़ी', flag: '🇮🇳', region: 'Asia' },
  { code: 'hne-IN', name: 'Chhattisgarhi (India)', nativeName: 'छत्तीसगढ़ी', flag: '🇮🇳', region: 'Asia' },
  { code: 'mag-IN', name: 'Magahi (India)', nativeName: 'मगही', flag: '🇮🇳', region: 'Asia' },
  { code: 'bgc-IN', name: 'Haryanvi (India)', nativeName: 'हरियाणवी', flag: '🇮🇳', region: 'Asia' },
  { code: 'tcy-IN', name: 'Tulu (India)', nativeName: 'ತುಳು', flag: '🇮🇳', region: 'Asia' },
  { code: 'dz-BT', name: 'Dzongkha (Bhutan)', nativeName: 'རྫོང་ཁ', flag: '🇧🇹', region: 'Asia' },
  { code: 'si-LK', name: 'Sinhala (Sri Lanka)', nativeName: 'සිංහල', flag: '🇱🇰', region: 'Asia' },
  { code: 'dv-MV', name: 'Divehi / Maldivian (Maldives)', nativeName: 'ދިވެހި', flag: '🇲🇻', region: 'Asia', rtl: true },

  // ==========================================
  // EAST & SOUTHEAST ASIAN LANGUAGES
  // ==========================================
  { code: 'ja-JP', name: 'Japanese (Japan)', nativeName: '日本語', flag: '🇯🇵', region: 'Asia' },
  { code: 'ko-KR', name: 'Korean (South Korea)', nativeName: '한국어', flag: '🇰🇷', region: 'Asia' },
  { code: 'ko-KP', name: 'Korean (North Korea)', nativeName: '조선말', flag: '🇰🇵', region: 'Asia' },
  { code: 'id-ID', name: 'Indonesian (Indonesia)', nativeName: 'Bahasa Indonesia', flag: '🇮🇩', region: 'Asia' },
  { code: 'ms-MY', name: 'Malay (Malaysia)', nativeName: 'Bahasa Melayu (Malaysia)', flag: '🇲🇾', region: 'Asia' },
  { code: 'ms-BN', name: 'Malay (Brunei)', nativeName: 'Bahasa Melayu (Brunei)', flag: '🇧🇳', region: 'Asia' },
  { code: 'ms-SG', name: 'Malay (Singapore)', nativeName: 'Bahasa Melayu (Singapura)', flag: '🇸🇬', region: 'Asia' },
  { code: 'vi-VN', name: 'Vietnamese (Vietnam)', nativeName: 'Tiếng Việt', flag: '🇻🇳', region: 'Asia' },
  { code: 'th-TH', name: 'Thai (Thailand)', nativeName: 'ไทย', flag: '🇹🇭', region: 'Asia' },
  { code: 'fil-PH', name: 'Filipino / Tagalog (Philippines)', nativeName: 'Wikang Filipino / Tagalog', flag: '🇵🇭', region: 'Asia' },
  { code: 'ceb-PH', name: 'Cebuano / Bisaya (Philippines)', nativeName: 'Binisaya / Sinugboanon', flag: '🇵🇭', region: 'Asia' },
  { code: 'ilo-PH', name: 'Ilocano (Philippines)', nativeName: 'Ilokano', flag: '🇵🇭', region: 'Asia' },
  { code: 'hil-PH', name: 'Hiligaynon / Ilonggo (Philippines)', nativeName: 'Ilonggo', flag: '🇵🇭', region: 'Asia' },
  { code: 'war-PH', name: 'Waray-Waray (Philippines)', nativeName: 'Winaray', flag: '🇵🇭', region: 'Asia' },
  { code: 'bik-PH', name: 'Bikol (Philippines)', nativeName: 'Bikol', flag: '🇵🇭', region: 'Asia' },
  { code: 'pam-PH', name: 'Kapampangan (Philippines)', nativeName: 'Kapampangan', flag: '🇵🇭', region: 'Asia' },
  { code: 'pag-PH', name: 'Pangasinan (Philippines)', nativeName: 'Pangasinan', flag: '🇵🇭', region: 'Asia' },
  { code: 'cbk-PH', name: 'Chavacano (Philippines)', nativeName: 'Chavacano de Zamboanga', flag: '🇵🇭', region: 'Asia' },
  { code: 'jv-ID', name: 'Javanese (Indonesia)', nativeName: 'Basa Jawa', flag: '🇮🇩', region: 'Asia' },
  { code: 'su-ID', name: 'Sundanese (Indonesia)', nativeName: 'Basa Sunda', flag: '🇮🇩', region: 'Asia' },
  { code: 'mad-ID', name: 'Madurese (Indonesia)', nativeName: 'Bhasa Madhura', flag: '🇮🇩', region: 'Asia' },
  { code: 'min-ID', name: 'Minangkabau (Indonesia)', nativeName: 'Baso Minang', flag: '🇮🇩', region: 'Asia' },
  { code: 'ban-ID', name: 'Balinese (Indonesia)', nativeName: 'Basä Bali', flag: '🇮🇩', region: 'Asia' },
  { code: 'bug-ID', name: 'Buginese (Indonesia)', nativeName: 'Basa Ugi', flag: '🇮🇩', region: 'Asia' },
  { code: 'bjn-ID', name: 'Banjarese (Indonesia)', nativeName: 'Bahasa Banjar', flag: '🇮🇩', region: 'Asia' },
  { code: 'ace-ID', name: 'Acehnese (Indonesia)', nativeName: 'Bahsa Acèh', flag: '🇮🇩', region: 'Asia' },
  { code: 'km-KH', name: 'Khmer (Cambodia)', nativeName: 'ភាសាខ្មែរ', flag: '🇰🇭', region: 'Asia' },
  { code: 'lo-LA', name: 'Lao (Laos)', nativeName: 'ພາສາລາວ', flag: '🇱🇦', region: 'Asia' },
  { code: 'my-MM', name: 'Burmese (Myanmar)', nativeName: 'မြန်မာစာ', flag: '🇲🇲', region: 'Asia' },
  { code: 'shn-MM', name: 'Shan (Myanmar)', nativeName: 'လိၵ်ႈတႆး', flag: '🇲🇲', region: 'Asia' },
  { code: 'ksw-MM', name: 'S\'gaw Karen (Myanmar)', nativeName: 'ကညီစှီၤကျိာ်', flag: '🇲🇲', region: 'Asia' },
  { code: 'mnw-MM', name: 'Mon (Myanmar)', nativeName: 'ဘာသာမန်', flag: '🇲🇲', region: 'Asia' },
  { code: 'tet-TL', name: 'Tetum (Timor-Leste)', nativeName: 'Lia-Tetun', flag: '🇹🇱', region: 'Asia' },
  { code: 'hmn', name: 'Hmong (Southeast Asia)', nativeName: 'Hmoob', flag: '🇱🇦', region: 'Asia' },

  // ==========================================
  // CENTRAL ASIAN & CAUCASUS LANGUAGES
  // ==========================================
  { code: 'kk-KZ', name: 'Kazakh (Kazakhstan)', nativeName: 'Қазақ тілі', flag: '🇰🇿', region: 'Central Asia' },
  { code: 'uz-UZ', name: 'Uzbek (Uzbekistan)', nativeName: 'Oʻzbek tili / Ўзбек тили', flag: '🇺🇿', region: 'Central Asia' },
  { code: 'ky-KG', name: 'Kyrgyz (Kyrgyzstan)', nativeName: 'Кыргызча', flag: '🇰🇬', region: 'Central Asia' },
  { code: 'tg-TJ', name: 'Tajik (Tajikistan)', nativeName: 'Тоҷикӣ', flag: '🇹🇯', region: 'Central Asia' },
  { code: 'tk-TM', name: 'Turkmen (Turkmenistan)', nativeName: 'Türkmençe', flag: '🇹🇲', region: 'Central Asia' },
  { code: 'mn-MN', name: 'Mongolian (Mongolia)', nativeName: 'Монгол хэл', flag: '🇲🇳', region: 'Central Asia' },
  { code: 'az-AZ', name: 'Azerbaijani (Azerbaijan)', nativeName: 'Azərbaycan dili', flag: '🇦🇿', region: 'Caucasus / Asia' },
  { code: 'ka-GE', name: 'Georgian (Georgia)', nativeName: 'ქართული', flag: '🇬🇪', region: 'Caucasus / Europe' },
  { code: 'hy-AM', name: 'Armenian (Armenia)', nativeName: 'Հայերեն', flag: '🇦🇲', region: 'Caucasus / Europe' },
  { code: 'ug-CN', name: 'Uyghur (Xinjiang)', nativeName: 'ئۇيغۇرچە', flag: '🇨🇳', region: 'Central Asia', rtl: true },
  { code: 'bo-CN', name: 'Tibetan (Tibet)', nativeName: 'བོད་སྐད', flag: '🇨🇳', region: 'Asia' },
  { code: 'tt-RU', name: 'Tatar (Tatarstan)', nativeName: 'Татар теле', flag: '🇷🇺', region: 'Europe / Asia' },
  { code: 'ba-RU', name: 'Bashkir (Russia)', nativeName: 'Башҡорт теле', flag: '🇷🇺', region: 'Europe / Asia' },
  { code: 'ce-RU', name: 'Chechen (Chechnya)', nativeName: 'Нохчийн мотт', flag: '🇷🇺', region: 'Caucasus' },
  { code: 'os-RU', name: 'Ossetian (Caucasus)', nativeName: 'Ирон ӕвзаг', flag: '🇷🇺', region: 'Caucasus' },
  { code: 'cv-RU', name: 'Chuvash (Russia)', nativeName: 'Чӑваш чӗлхи', flag: '🇷🇺', region: 'Europe / Asia' },
  { code: 'sah-RU', name: 'Sakha / Yakut (Siberia)', nativeName: 'Саха тыла', flag: '🇷🇺', region: 'Asia' },
  { code: 'tyv-RU', name: 'Tuvan (Tuva)', nativeName: 'Тыва дыл', flag: '🇷🇺', region: 'Asia' },
  { code: 'av-RU', name: 'Avar (Dagestan)', nativeName: 'Авар мацӏ', flag: '🇷🇺', region: 'Caucasus' },
  { code: 'kum-RU', name: 'Kumyk (Dagestan)', nativeName: 'Къумукъ тил', flag: '🇷🇺', region: 'Caucasus' },

  // ==========================================
  // MIDDLE EASTERN & IRANIC LANGUAGES
  // ==========================================
  { code: 'fa-IR', name: 'Persian / Farsi (Iran)', nativeName: 'فارسی', flag: '🇮🇷', region: 'Middle East', rtl: true },
  { code: 'prs-AF', name: 'Dari (Afghanistan)', nativeName: 'دری', flag: '🇦🇫', region: 'Middle East / Asia', rtl: true },
  { code: 'ps-AF', name: 'Pashto (Afghanistan / Pakistan)', nativeName: 'پښتو', flag: '🇦🇫', region: 'Middle East / Asia', rtl: true },
  { code: 'tr-TR', name: 'Turkish (Turkey)', nativeName: 'Türkçe (Türkiye)', flag: '🇹🇷', region: 'Europe / Asia' },
  { code: 'tr-CY', name: 'Turkish (Northern Cyprus)', nativeName: 'Türkçe (Kıbrıs)', flag: '🇨🇾', region: 'Europe' },
  { code: 'he-IL', name: 'Hebrew (Israel)', nativeName: 'עברית', flag: '🇮🇱', region: 'Middle East', rtl: true },
  { code: 'ku-TR', name: 'Kurdish - Kurmanji (Latin script)', nativeName: 'Kurdî (Kurmancî)', flag: '🇹🇷', region: 'Middle East' },
  { code: 'ckb-IQ', name: 'Kurdish - Sorani (Arabic script)', nativeName: 'کوردی (سۆرانی)', flag: '🇮🇶', region: 'Middle East', rtl: true },
  { code: 'bal-PK', name: 'Balochi (Pakistan / Iran)', nativeName: 'بلوچی', flag: '🇵🇰', region: 'Asia', rtl: true },
  { code: 'syr', name: 'Syriac / Aramaic (Middle East)', nativeName: 'ܣܘܪܝܝܐ', flag: '🇸🇾', region: 'Middle East', rtl: true },

  // ==========================================
  // EUROPEAN NATIONAL & REGIONAL LANGUAGES
  // ==========================================
  { code: 'it-IT', name: 'Italian (Italy)', nativeName: 'Italiano (Italia)', flag: '🇮🇹', region: 'Europe' },
  { code: 'it-CH', name: 'Italian (Switzerland)', nativeName: 'Italiano (Svizzera)', flag: '🇨🇭', region: 'Europe' },
  { code: 'it-SM', name: 'Italian (San Marino)', nativeName: 'Italiano (San Marino)', flag: '🇸🇲', region: 'Europe' },
  { code: 'it-VA', name: 'Italian (Vatican City)', nativeName: 'Italiano (Vaticano)', flag: '🇻🇦', region: 'Europe' },
  { code: 'ru-RU', name: 'Russian (Russia)', nativeName: 'Русский (Россия)', flag: '🇷🇺', region: 'Europe / Asia' },
  { code: 'ru-BY', name: 'Russian (Belarus)', nativeName: 'Русский (Беларусь)', flag: '🇧🇾', region: 'Europe' },
  { code: 'ru-KZ', name: 'Russian (Kazakhstan)', nativeName: 'Русский (Казахстан)', flag: '🇰🇿', region: 'Central Asia' },
  { code: 'ru-KG', name: 'Russian (Kyrgyzstan)', nativeName: 'Русский (Кыргызстан)', flag: '🇰🇬', region: 'Central Asia' },
  { code: 'uk-UA', name: 'Ukrainian (Ukraine)', nativeName: 'Українська', flag: '🇺🇦', region: 'Europe' },
  { code: 'be-BY', name: 'Belarusian (Belarus)', nativeName: 'Беларуская', flag: '🇧🇾', region: 'Europe' },
  { code: 'pl-PL', name: 'Polish (Poland)', nativeName: 'Polski', flag: '🇵🇱', region: 'Europe' },
  { code: 'nl-NL', name: 'Dutch (Netherlands)', nativeName: 'Nederlands (Nederland)', flag: '🇳🇱', region: 'Europe' },
  { code: 'nl-BE', name: 'Dutch / Flemish (Belgium)', nativeName: 'Nederlands (Vlaams)', flag: '🇧🇪', region: 'Europe' },
  { code: 'nl-SR', name: 'Dutch (Suriname)', nativeName: 'Nederlands (Suriname)', flag: '🇸🇷', region: 'Americas' },
  { code: 'sv-SE', name: 'Swedish (Sweden)', nativeName: 'Svenska (Sverige)', flag: '🇸🇪', region: 'Europe' },
  { code: 'sv-FI', name: 'Swedish (Finland)', nativeName: 'Svenska (Finland)', flag: '🇫🇮', region: 'Europe' },
  { code: 'no-NO', name: 'Norwegian Bokmål (Norway)', nativeName: 'Norsk Bokmål', flag: '🇳🇴', region: 'Europe' },
  { code: 'nn-NO', name: 'Norwegian Nynorsk (Norway)', nativeName: 'Norsk Nynorsk', flag: '🇳🇴', region: 'Europe' },
  { code: 'da-DK', name: 'Danish (Denmark)', nativeName: 'Dansk (Danmark)', flag: '🇩🇰', region: 'Europe' },
  { code: 'da-GL', name: 'Danish (Greenland)', nativeName: 'Dansk (Grønland)', flag: '🇬🇱', region: 'Europe' },
  { code: 'fi-FI', name: 'Finnish (Finland)', nativeName: 'Suomi', flag: '🇫🇮', region: 'Europe' },
  { code: 'is-IS', name: 'Icelandic (Iceland)', nativeName: 'Íslenska', flag: '🇮🇸', region: 'Europe' },
  { code: 'fo-FO', name: 'Faroese (Faroe Islands)', nativeName: 'Føroyskt', flag: '🇫🇴', region: 'Europe' },
  { code: 'el-GR', name: 'Greek (Greece)', nativeName: 'Ελληνικά (Ελλάδα)', flag: '🇬🇷', region: 'Europe' },
  { code: 'el-CY', name: 'Greek (Cyprus)', nativeName: 'Ελληνικά (Κύπρος)', flag: '🇨🇾', region: 'Europe' },
  { code: 'cs-CZ', name: 'Czech (Czechia)', nativeName: 'Čeština', flag: '🇨🇿', region: 'Europe' },
  { code: 'sk-SK', name: 'Slovak (Slovakia)', nativeName: 'Slovenčina', flag: '🇸🇰', region: 'Europe' },
  { code: 'hu-HU', name: 'Hungarian (Hungary)', nativeName: 'Magyar', flag: '🇭🇺', region: 'Europe' },
  { code: 'ro-RO', name: 'Romanian (Romania)', nativeName: 'Română (România)', flag: '🇷🇴', region: 'Europe' },
  { code: 'ro-MD', name: 'Romanian / Moldovan (Moldova)', nativeName: 'Română (Moldova)', flag: '🇲🇩', region: 'Europe' },
  { code: 'bg-BG', name: 'Bulgarian (Bulgaria)', nativeName: 'Български', flag: '🇧🇬', region: 'Europe' },
  { code: 'sr-RS', name: 'Serbian (Cyrillic - Serbia)', nativeName: 'Српски (ћирилица)', flag: '🇷🇸', region: 'Europe' },
  { code: 'sr-Latn-RS', name: 'Serbian (Latin - Serbia)', nativeName: 'Srpski (latinica)', flag: '🇷🇸', region: 'Europe' },
  { code: 'hr-HR', name: 'Croatian (Croatia)', nativeName: 'Hrvatski (Hrvatska)', flag: '🇭🇷', region: 'Europe' },
  { code: 'hr-BA', name: 'Croatian (Bosnia)', nativeName: 'Hrvatski (BiH)', flag: '🇧🇦', region: 'Europe' },
  { code: 'bs-BA', name: 'Bosnian (Bosnia & Herzegovina)', nativeName: 'Bosanski', flag: '🇧🇦', region: 'Europe' },
  { code: 'sl-SI', name: 'Slovenian (Slovenia)', nativeName: 'Slovenščina', flag: '🇸🇮', region: 'Europe' },
  { code: 'mk-MK', name: 'Macedonian (North Macedonia)', nativeName: 'Македонски', flag: '🇲🇰', region: 'Europe' },
  { code: 'sq-AL', name: 'Albanian (Albania)', nativeName: 'Shqip (Shqipëri)', flag: '🇦🇱', region: 'Europe' },
  { code: 'sq-XK', name: 'Albanian (Kosovo)', nativeName: 'Shqip (Kosovë)', flag: '🇽🇰', region: 'Europe' },
  { code: 'sq-MK', name: 'Albanian (North Macedonia)', nativeName: 'Shqip (Maqedoni)', flag: '🇲🇰', region: 'Europe' },
  { code: 'cnr-ME', name: 'Montenegrin (Montenegro)', nativeName: 'Crnogorski', flag: '🇲🇪', region: 'Europe' },
  { code: 'et-EE', name: 'Estonian (Estonia)', nativeName: 'Eesti', flag: '🇪🇪', region: 'Europe' },
  { code: 'lv-LV', name: 'Latvian (Latvia)', nativeName: 'Latviešu', flag: '🇱🇻', region: 'Europe' },
  { code: 'lt-LT', name: 'Lithuanian (Lithuania)', nativeName: 'Lietuvių', flag: '🇱🇹', region: 'Europe' },
  { code: 'mt-MT', name: 'Maltese (Malta)', nativeName: 'Malti', flag: '🇲🇹', region: 'Europe' },
  { code: 'lb-LU', name: 'Luxembourgish (Luxembourg)', nativeName: 'Lëtzebuergesch', flag: '🇱🇺', region: 'Europe' },
  { code: 'ga-IE', name: 'Irish Gaelic (Ireland)', nativeName: 'Gaeilge', flag: '🇮🇪', region: 'Europe' },
  { code: 'cy-GB', name: 'Welsh (Wales / UK)', nativeName: 'Cymraeg', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', region: 'Europe' },
  { code: 'gd-GB', name: 'Scottish Gaelic (Scotland / UK)', nativeName: 'Gàidhlig', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', region: 'Europe' },
  { code: 'sco', name: 'Scots (Scotland)', nativeName: 'Scots leid', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', region: 'Europe' },
  { code: 'gv', name: 'Manx (Isle of Man)', nativeName: 'Gaelg', flag: '🇮🇲', region: 'Europe' },
  { code: 'kw', name: 'Cornish (Cornwall)', nativeName: 'Kernewek', flag: '🇬🇧', region: 'Europe' },
  { code: 'ca-ES', name: 'Catalan (Catalonia / Spain)', nativeName: 'Català', flag: '🇪🇸', region: 'Europe' },
  { code: 'ca-AD', name: 'Catalan (Andorra)', nativeName: 'Català (Andorra)', flag: '🇦🇩', region: 'Europe' },
  { code: 'ca-FR', name: 'Catalan (Roussillon / France)', nativeName: 'Català (França)', flag: '🇫🇷', region: 'Europe' },
  { code: 'ca-IT', name: 'Catalan (Alghero / Italy)', nativeName: 'Català (Alguer)', flag: '🇮🇹', region: 'Europe' },
  { code: 'eu-ES', name: 'Basque (Euskadi / Spain & France)', nativeName: 'Euskara', flag: '🇪🇸', region: 'Europe' },
  { code: 'gl-ES', name: 'Galician (Galicia / Spain)', nativeName: 'Galego', flag: '🇪🇸', region: 'Europe' },
  { code: 'ast-ES', name: 'Asturian (Asturias / Spain)', nativeName: 'Asturianu', flag: '🇪🇸', region: 'Europe' },
  { code: 'an-ES', name: 'Aragonese (Aragon / Spain)', nativeName: 'Aragonés', flag: '🇪🇸', region: 'Europe' },
  { code: 'oc-FR', name: 'Occitan / Provençal (France)', nativeName: 'Occitan', flag: '🇫🇷', region: 'Europe' },
  { code: 'br-FR', name: 'Breton (Brittany / France)', nativeName: 'Brezhoneg', flag: '🇫🇷', region: 'Europe' },
  { code: 'co-FR', name: 'Corsican (Corsica / France)', nativeName: 'Corsu', flag: '🇫🇷', region: 'Europe' },
  { code: 'sc-IT', name: 'Sardinian (Sardinia / Italy)', nativeName: 'Sardu', flag: '🇮🇹', region: 'Europe' },
  { code: 'scn-IT', name: 'Sicilian (Sicily / Italy)', nativeName: 'Sicilianu', flag: '🇮🇹', region: 'Europe' },
  { code: 'vec-IT', name: 'Venetian (Veneto / Italy)', nativeName: 'Vèneto', flag: '🇮🇹', region: 'Europe' },
  { code: 'lmo-IT', name: 'Lombard (Lombardy / Italy)', nativeName: 'Lumbard', flag: '🇮🇹', region: 'Europe' },
  { code: 'nap-IT', name: 'Neapolitan (Naples / Italy)', nativeName: 'Nnapulitano', flag: '🇮🇹', region: 'Europe' },
  { code: 'pms-IT', name: 'Piedmontese (Piedmont / Italy)', nativeName: 'Piemontèis', flag: '🇮🇹', region: 'Europe' },
  { code: 'fur-IT', name: 'Friulian (Friuli / Italy)', nativeName: 'Furlan', flag: '🇮🇹', region: 'Europe' },
  { code: 'rm-CH', name: 'Romansh (Switzerland)', nativeName: 'Rumantsch', flag: '🇨🇭', region: 'Europe' },
  { code: 'gsw-CH', name: 'Swiss German (Schwiizerdütsch)', nativeName: 'Schwiizerdütsch', flag: '🇨🇭', region: 'Europe' },
  { code: 'bar-DE', name: 'Bavarian (Bavaria & Austria)', nativeName: 'Boarisch', flag: '🇩🇪', region: 'Europe' },
  { code: 'nds-DE', name: 'Low German / Low Saxon', nativeName: 'Plattdüütsch', flag: '🇩🇪', region: 'Europe' },
  { code: 'fy-NL', name: 'Western Frisian (Netherlands)', nativeName: 'Frysk', flag: '🇳🇱', region: 'Europe' },
  { code: 'li-NL', name: 'Limburgish (Netherlands / Belgium)', nativeName: 'Limburgs', flag: '🇳🇱', region: 'Europe' },
  { code: 'wa-BE', name: 'Walloon (Wallonia / Belgium)', nativeName: 'Walon', flag: '🇧🇪', region: 'Europe' },
  { code: 'csb-PL', name: 'Kashubian (Poland)', nativeName: 'Kaszëbsczi', flag: '🇵🇱', region: 'Europe' },
  { code: 'szl-PL', name: 'Silesian (Poland)', nativeName: 'Ślōnski', flag: '🇵🇱', region: 'Europe' },
  { code: 'hsb-DE', name: 'Upper Sorbian (Germany)', nativeName: 'Hornjoserbšćina', flag: '🇩🇪', region: 'Europe' },
  { code: 'dsb-DE', name: 'Lower Sorbian (Germany)', nativeName: 'Dolnoserbšćina', flag: '🇩🇪', region: 'Europe' },
  { code: 'rue', name: 'Rusyn (Carpathian Europe)', nativeName: 'Русиньскый язык', flag: '🇺🇦', region: 'Europe' },
  { code: 'gag-MD', name: 'Gagauz (Moldova)', nativeName: 'Gagauz dili', flag: '🇲🇩', region: 'Europe' },
  { code: 'sme-NO', name: 'Northern Sami (Norway / Sweden / Finland)', nativeName: 'Davvisámegiella', flag: '🇳🇴', region: 'Europe' },
  { code: 'smj-SE', name: 'Lule Sami (Sweden / Norway)', nativeName: 'Julevsámegiella', flag: '🇸🇪', region: 'Europe' },
  { code: 'smn-FI', name: 'Inari Sami (Finland)', nativeName: 'Anarâškielâ', flag: '🇫🇮', region: 'Europe' },
  { code: 'sms-FI', name: 'Skolt Sami (Finland)', nativeName: 'Nuortalašǩiõll', flag: '🇫🇮', region: 'Europe' },

  // ==========================================
  // SUB-SAHARAN & NORTH AFRICAN LANGUAGES
  // ==========================================
  { code: 'sw-KE', name: 'Swahili (Kenya)', nativeName: 'Kiswahili (Kenya)', flag: '🇰🇪', region: 'Africa' },
  { code: 'sw-TZ', name: 'Swahili (Tanzania)', nativeName: 'Kiswahili (Tanzania)', flag: '🇹🇿', region: 'Africa' },
  { code: 'sw-UG', name: 'Swahili (Uganda)', nativeName: 'Kiswahili (Uganda)', flag: '🇺🇬', region: 'Africa' },
  { code: 'sw-CD', name: 'Swahili (DR Congo)', nativeName: 'Kiswahili (RD Congo)', flag: '🇨🇩', region: 'Africa' },
  { code: 'sw-RW', name: 'Swahili (Rwanda)', nativeName: 'Kiswahili (Rwanda)', flag: '🇷🇼', region: 'Africa' },
  { code: 'ha-NG', name: 'Hausa (Nigeria)', nativeName: 'Harshen Hausa', flag: '🇳🇬', region: 'Africa' },
  { code: 'ha-NE', name: 'Hausa (Niger)', nativeName: 'Hausa (Nijar)', flag: '🇳🇪', region: 'Africa' },
  { code: 'ha-GH', name: 'Hausa (Ghana)', nativeName: 'Hausa (Ghana)', flag: '🇬🇭', region: 'Africa' },
  { code: 'yo-NG', name: 'Yoruba (Nigeria & Benin)', nativeName: 'Èdè Yorùbá', flag: '🇳🇬', region: 'Africa' },
  { code: 'ig-NG', name: 'Igbo (Nigeria)', nativeName: 'Asụsụ Igbo', flag: '🇳🇬', region: 'Africa' },
  { code: 'pcm-NG', name: 'Nigerian Pidgin English', nativeName: 'Naijá / Broken English', flag: '🇳🇬', region: 'Africa' },
  { code: 'am-ET', name: 'Amharic (Ethiopia)', nativeName: 'አማርኛ', flag: '🇪🇹', region: 'Africa' },
  { code: 'om-ET', name: 'Oromo (Ethiopia & Kenya)', nativeName: 'Afaan Oromoo', flag: '🇪🇹', region: 'Africa' },
  { code: 'ti-ET', name: 'Tigrinya (Ethiopia)', nativeName: 'ትግርኛ (ኢትዮጵያ)', flag: '🇪🇹', region: 'Africa' },
  { code: 'ti-ER', name: 'Tigrinya (Eritrea)', nativeName: 'ትግርኛ (ኤርትራ)', flag: '🇪🇷', region: 'Africa' },
  { code: 'so-SO', name: 'Somali (Somalia)', nativeName: 'Af-Soomaali (Soomaaliya)', flag: '🇸🇴', region: 'Africa' },
  { code: 'so-DJ', name: 'Somali (Djibouti)', nativeName: 'Af-Soomaali (Jabuuti)', flag: '🇩🇯', region: 'Africa' },
  { code: 'so-ET', name: 'Somali (Ethiopia)', nativeName: 'Af-Soomaali (Itoobiya)', flag: '🇪🇹', region: 'Africa' },
  { code: 'so-KE', name: 'Somali (Kenya)', nativeName: 'Af-Soomaali (Kiiniya)', flag: '🇰🇪', region: 'Africa' },
  { code: 'aa-ET', name: 'Afar (Ethiopia / Djibouti / Eritrea)', nativeName: 'Qafaraf', flag: '🇩🇯', region: 'Africa' },
  { code: 'zu-ZA', name: 'Zulu / isiZulu (South Africa)', nativeName: 'isiZulu', flag: '🇿🇦', region: 'Africa' },
  { code: 'xh-ZA', name: 'Xhosa / isiXhosa (South Africa)', nativeName: 'isiXhosa', flag: '🇿🇦', region: 'Africa' },
  { code: 'af-ZA', name: 'Afrikaans (South Africa & Namibia)', nativeName: 'Afrikaans', flag: '🇿🇦', region: 'Africa' },
  { code: 'st-ZA', name: 'Southern Sotho / Sesotho (South Africa & Lesotho)', nativeName: 'Sesotho', flag: '🇱🇸', region: 'Africa' },
  { code: 'nso-ZA', name: 'Northern Sotho / Sepedi (South Africa)', nativeName: 'Sepedi', flag: '🇿🇦', region: 'Africa' },
  { code: 'tn-BW', name: 'Setswana / Tswana (Botswana & South Africa)', nativeName: 'Setswana', flag: '🇧🇼', region: 'Africa' },
  { code: 'ts-ZA', name: 'Tsonga / Xitsonga (South Africa & Mozambique)', nativeName: 'Xitsonga', flag: '🇿🇦', region: 'Africa' },
  { code: 'ss-SZ', name: 'Swati / siSwati (Eswatini & South Africa)', nativeName: 'siSwati', flag: '🇸🇿', region: 'Africa' },
  { code: 've-ZA', name: 'Venda / Tshivenḓa (South Africa)', nativeName: 'Tshivenḓa', flag: '🇿🇦', region: 'Africa' },
  { code: 'nr-ZA', name: 'Southern Ndebele / isiNdebele (South Africa)', nativeName: 'isiNdebele', flag: '🇿🇦', region: 'Africa' },
  { code: 'sn-ZW', name: 'Shona (Zimbabwe)', nativeName: 'chiShona', flag: '🇿🇼', region: 'Africa' },
  { code: 'nd-ZW', name: 'Northern Ndebele (Zimbabwe)', nativeName: 'isiNdebele (Zimbabwe)', flag: '🇿🇼', region: 'Africa' },
  { code: 'ny-MW', name: 'Chichewa / Nyanja (Malawi & Zambia)', nativeName: 'ChiCheŵa', flag: '🇲🇼', region: 'Africa' },
  { code: 'bem-ZM', name: 'Bemba / Chibemba (Zambia)', nativeName: 'Ichibemba', flag: '🇿🇲', region: 'Africa' },
  { code: 'loz-ZM', name: 'Lozi / Silozi (Zambia & Namibia)', nativeName: 'Silozi', flag: '🇿🇲', region: 'Africa' },
  { code: 'ton-ZM', name: 'Tonga (Zambia & Zimbabwe)', nativeName: 'Chitonga', flag: '🇿🇲', region: 'Africa' },
  { code: 'ln-CD', name: 'Lingala (DR Congo & Congo-Brazzaville)', nativeName: 'Lingála', flag: '🇨🇩', region: 'Africa' },
  { code: 'kg-CD', name: 'Kongo / Kikongo (DR Congo & Angola)', nativeName: 'Kikongo', flag: '🇨🇩', region: 'Africa' },
  { code: 'lua-CD', name: 'Tshiluba / Luba-Kasai (DR Congo)', nativeName: 'Tshiluba', flag: '🇨🇩', region: 'Africa' },
  { code: 'rw-RW', name: 'Kinyarwanda (Rwanda)', nativeName: 'Ikinyarwanda', flag: '🇷🇼', region: 'Africa' },
  { code: 'rn-BI', name: 'Kirundi (Burundi)', nativeName: 'Ikirundi', flag: '🇧🇮', region: 'Africa' },
  { code: 'lg-UG', name: 'Luganda / Ganda (Uganda)', nativeName: 'Oluganda', flag: '🇺🇬', region: 'Africa' },
  { code: 'ach-UG', name: 'Acholi (Uganda & South Sudan)', nativeName: 'Lwo / Acoli', flag: '🇺🇬', region: 'Africa' },
  { code: 'teo-UG', name: 'Ateso (Uganda & Kenya)', nativeName: 'Ateso', flag: '🇺🇬', region: 'Africa' },
  { code: 'kik-KE', name: 'Kikuyu / Gikuyu (Kenya)', nativeName: 'Gĩkũyũ', flag: '🇰🇪', region: 'Africa' },
  { code: 'luo-KE', name: 'Luo / Dholuo (Kenya & Tanzania)', nativeName: 'Dholuo', flag: '🇰🇪', region: 'Africa' },
  { code: 'luy-KE', name: 'Luhya (Kenya)', nativeName: 'Luluhya', flag: '🇰🇪', region: 'Africa' },
  { code: 'kam-KE', name: 'Kamba (Kenya)', nativeName: 'Kikamba', flag: '🇰🇪', region: 'Africa' },
  { code: 'kal-KE', name: 'Kalenjin (Kenya)', nativeName: 'Kalenjin', flag: '🇰🇪', region: 'Africa' },
  { code: 'mer-KE', name: 'Meru / Kimeru (Kenya)', nativeName: 'Kĩmĩrũ', flag: '🇰🇪', region: 'Africa' },
  { code: 'mas-KE', name: 'Maasai (Kenya & Tanzania)', nativeName: 'ɔl-Maa', flag: '🇰🇪', region: 'Africa' },
  { code: 'suk-TZ', name: 'Sukuma (Tanzania)', nativeName: 'Kisukuma', flag: '🇹🇿', region: 'Africa' },
  { code: 'chg-TZ', name: 'Chaga (Tanzania)', nativeName: 'Kichaga', flag: '🇹🇿', region: 'Africa' },
  { code: 'tw-GH', name: 'Twi / Akan (Ghana)', nativeName: 'Twi / Akan', flag: '🇬🇭', region: 'Africa' },
  { code: 'fat-GH', name: 'Fante (Ghana)', nativeName: 'Mfantse', flag: '🇬🇭', region: 'Africa' },
  { code: 'ee-GH', name: 'Ewe (Ghana & Togo)', nativeName: 'Èʋegbe', flag: '🇬🇭', region: 'Africa' },
  { code: 'gaa-GH', name: 'Ga (Ghana)', nativeName: 'Ga', flag: '🇬🇭', region: 'Africa' },
  { code: 'dag-GH', name: 'Dagbani (Ghana)', nativeName: 'Dagbanli', flag: '🇬🇭', region: 'Africa' },
  { code: 'gpe-GH', name: 'Ghanaian Pidgin English', nativeName: 'Ghana Pidgin', flag: '🇬🇭', region: 'Africa' },
  { code: 'bm-ML', name: 'Bambara / Bamanankan (Mali)', nativeName: 'Bamanankan', flag: '🇲🇱', region: 'Africa' },
  { code: 'wo-SN', name: 'Wolof (Senegal & Gambia)', nativeName: 'Wolof', flag: '🇸🇳', region: 'Africa' },
  { code: 'ff-SN', name: 'Fula / Fulfulde / Pulaar (West Africa)', nativeName: 'Pulaar / Fulfulde', flag: '🇸🇳', region: 'Africa' },
  { code: 'ff-NG', name: 'Fulfulde (Nigeria)', nativeName: 'Fulfulde (Nigeria)', flag: '🇳🇬', region: 'Africa' },
  { code: 'mnk-GM', name: 'Mandinka (Gambia & Senegal)', nativeName: 'Mandi\'nka kango', flag: '🇬🇲', region: 'Africa' },
  { code: 'man-GN', name: 'Malinke / Maninka (Guinea & Mali)', nativeName: 'Maninkakan', flag: '🇬🇳', region: 'Africa' },
  { code: 'mos-BF', name: 'Mossi / Mooré (Burkina Faso)', nativeName: 'Mòoré', flag: '🇧🇫', region: 'Africa' },
  { code: 'dyu-CI', name: 'Dyula / Jula (Côte d’Ivoire & Burkina Faso)', nativeName: 'Julakan', flag: '🇨🇮', region: 'Africa' },
  { code: 'baul-CI', name: 'Baoulé (Côte d’Ivoire)', nativeName: 'Bawule', flag: '🇨🇮', region: 'Africa' },
  { code: 'fon-BJ', name: 'Fon (Benin)', nativeName: 'Fɔngbe', flag: '🇧🇯', region: 'Africa' },
  { code: 'kbp-TG', name: 'Kabiye (Togo)', nativeName: 'Kabɩyɛ', flag: '🇹🇬', region: 'Africa' },
  { code: 'sg-CF', name: 'Sango (Central African Republic)', nativeName: 'Sängö', flag: '🇨🇫', region: 'Africa' },
  { code: 'fan-GA', name: 'Fang (Gabon & Equatorial Guinea)', nativeName: 'Pahuin / Fang', flag: '🇬🇦', region: 'Africa' },
  { code: 'dua-CM', name: 'Duala (Cameroon)', nativeName: 'Duala', flag: '🇨🇲', region: 'Africa' },
  { code: 'ewo-CM', name: 'Ewondo (Cameroon)', nativeName: 'Ewondo', flag: '🇨🇲', region: 'Africa' },
  { code: 'wes-CM', name: 'Cameroonian Pidgin (Kamtok)', nativeName: 'Kamtok', flag: '🇨🇲', region: 'Africa' },
  { code: 'kmb-AO', name: 'Kimbundu (Angola)', nativeName: 'Kimbundu', flag: '🇦🇴', region: 'Africa' },
  { code: 'umb-AO', name: 'Umbundu (Angola)', nativeName: 'Úmbúndú', flag: '🇦🇴', region: 'Africa' },
  { code: 'mak-MZ', name: 'Makhuwa (Mozambique)', nativeName: 'Emakhuwa', flag: '🇲🇿', region: 'Africa' },
  { code: 'tso-MZ', name: 'Changana / Shangaan (Mozambique)', nativeName: 'Xichangana', flag: '🇲🇿', region: 'Africa' },
  { code: 'sena-MZ', name: 'Sena (Mozambique)', nativeName: 'Chisena', flag: '🇲🇿', region: 'Africa' },
  { code: 'mg-MG', name: 'Malagasy (Madagascar)', nativeName: 'Fiteny Malagasy', flag: '🇲🇬', region: 'Africa' },
  { code: 'mfe-MU', name: 'Mauritian Creole (Mauritius)', nativeName: 'Kreol Morisien', flag: '🇲🇺', region: 'Africa' },
  { code: 'crs-SC', name: 'Seychellois Creole (Seychelles)', nativeName: 'Seselwa', flag: '🇸🇨', region: 'Africa' },
  { code: 'kea-CV', name: 'Cape Verdean Creole (Kriolu)', nativeName: 'Kriolu / Kabuverdianu', flag: '🇨🇻', region: 'Africa' },
  { code: 'cri-ST', name: 'Forro / São Tomense (São Tomé)', nativeName: 'Forro', flag: '🇸🇹', region: 'Africa' },
  { code: 'kmr-KM', name: 'Comorian / Shikomor (Comoros)', nativeName: 'Shikomori', flag: '🇰🇲', region: 'Africa' },
  { code: 'din-SS', name: 'Dinka (South Sudan)', nativeName: 'Thuɔŋjäŋ', flag: '🇸🇸', region: 'Africa' },
  { code: 'nus-SS', name: 'Nuer (South Sudan)', nativeName: 'Thok Naath', flag: '🇸🇸', region: 'Africa' },
  { code: 'shk-SS', name: 'Shilluk (South Sudan)', nativeName: 'Dhøg Cøllø', flag: '🇸🇸', region: 'Africa' },
  { code: 'zgh-MA', name: 'Standard Moroccan Tamazight / Berber', nativeName: 'ⵜⴰⵎⴰⵣⵉⵖⵜ', flag: '🇲🇦', region: 'North Africa' },
  { code: 'kab-DZ', name: 'Kabyle (Algeria)', nativeName: 'Taqbaylit', flag: '🇩🇿', region: 'North Africa' },
  { code: 'tzm-MA', name: 'Central Atlas Tamazight (Morocco)', nativeName: 'ⵜⴰⵎⴰⵣⵉⵖⵜ ⵏ ⵡⴰⵟⵍⴰⵚ', flag: '🇲🇦', region: 'North Africa' },
  { code: 'shi-MA', name: 'Tashelhit / Shilha (Morocco)', nativeName: 'Taclḥit / ⵜⴰⵛⵍⵃⵉⵜ', flag: '🇲🇦', region: 'North Africa' },
  { code: 'rif-MA', name: 'Riffian / Tarifit (Morocco)', nativeName: 'Tarifit', flag: '🇲🇦', region: 'North Africa' },
  { code: 'tmh-NE', name: 'Tuareg / Tamasheq (Niger & Mali)', nativeName: 'Tamasheq', flag: '🇳🇪', region: 'North Africa' },
  { code: 'zen-MR', name: 'Zenaga (Mauritania)', nativeName: 'Tudhungiyya', flag: '🇲🇷', region: 'North Africa' },
  { code: 'siw-EG', name: 'Siwi Berber (Siwa Oasis / Egypt)', nativeName: 'Jlan n Isiwiyen', flag: '🇪🇬', region: 'North Africa' },

  // ==========================================
  // AMERICAS & INDIGENOUS LANGUAGES
  // ==========================================
  { code: 'gn-PY', name: 'Guarani (Paraguay)', nativeName: 'Avañe\'ẽ', flag: '🇵🇾', region: 'Americas' },
  { code: 'qu-PE', name: 'Quechua (Peru)', nativeName: 'Runasimi (Piruw)', flag: '🇵🇪', region: 'Americas' },
  { code: 'qu-BO', name: 'Quechua (Bolivia)', nativeName: 'Qhichwa simi (Buliwya)', flag: '🇧🇴', region: 'Americas' },
  { code: 'qu-EC', name: 'Kichwa / Quichua (Ecuador)', nativeName: 'Kichwa (Ikwadur)', flag: '🇪🇨', region: 'Americas' },
  { code: 'ay-BO', name: 'Aymara (Bolivia & Peru)', nativeName: 'Aymar aru', flag: '🇧🇴', region: 'Americas' },
  { code: 'nah-MX', name: 'Nahuatl / Aztec (Mexico)', nativeName: 'Nāhuatlahtōlli', flag: '🇲🇽', region: 'Americas' },
  { code: 'yua-MX', name: 'Yucatec Maya (Mexico)', nativeName: 'Màaya t\'àan', flag: '🇲🇽', region: 'Americas' },
  { code: 'quc-GT', name: 'K\'iche\' Maya (Guatemala)', nativeName: 'Qatzijob\'al K\'iche\'', flag: '🇬🇹', region: 'Americas' },
  { code: 'kek-GT', name: 'Q\'eqchi\' Maya (Guatemala)', nativeName: 'Q\'eqchi\'', flag: '🇬🇹', region: 'Americas' },
  { code: 'cak-GT', name: 'Kaqchikel (Guatemala)', nativeName: 'Kaqchikel', flag: '🇬🇹', region: 'Americas' },
  { code: 'mam-GT', name: 'Mam (Guatemala)', nativeName: 'Qyol Mam', flag: '🇬🇹', region: 'Americas' },
  { code: 'tzh-MX', name: 'Tzeltal (Chiapas / Mexico)', nativeName: 'Bats\'il k\'op Tseltal', flag: '🇲🇽', region: 'Americas' },
  { code: 'tzo-MX', name: 'Tzotzil (Chiapas / Mexico)', nativeName: 'Bats\'i k\'op Tsotsil', flag: '🇲🇽', region: 'Americas' },
  { code: 'zap-MX', name: 'Zapotec (Oaxaca / Mexico)', nativeName: 'Diidxazá', flag: '🇲🇽', region: 'Americas' },
  { code: 'mix-MX', name: 'Mixtec (Oaxaca / Mexico)', nativeName: 'Tu\'un sávi', flag: '🇲🇽', region: 'Americas' },
  { code: 'oto-MX', name: 'Otomi (Hidalgo / Mexico)', nativeName: 'Hñähñu', flag: '🇲🇽', region: 'Americas' },
  { code: 'nv-US', name: 'Navajo / Diné Bizaad (USA)', nativeName: 'Diné bizaad', flag: '🇺🇸', region: 'Americas' },
  { code: 'chr-US', name: 'Cherokee (USA)', nativeName: 'ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ', flag: '🇺🇸', region: 'Americas' },
  { code: 'cr-CA', name: 'Cree (Canada)', nativeName: 'ᓀᐦᐃᔭᐍᐏᐱ / Nēhiyawēwin', flag: '🇨🇦', region: 'Americas' },
  { code: 'iu-CA', name: 'Inuktitut (Canada)', nativeName: 'ᐃᓄᒃᑎᑐᑦ', flag: '🇨🇦', region: 'Americas' },
  { code: 'kl-GL', name: 'Greenlandic / Kalaallisut (Greenland)', nativeName: 'Kalaallisut', flag: '🇬🇱', region: 'Americas / Europe' },
  { code: 'oj-CA', name: 'Ojibwe / Anishinaabemowin (Canada & USA)', nativeName: 'Anishinaabemowin', flag: '🇨🇦', region: 'Americas' },
  { code: 'dak-US', name: 'Dakota / Lakota (USA)', nativeName: 'Lakȟólʼiya', flag: '🇺🇸', region: 'Americas' },
  { code: 'arn-CL', name: 'Mapudungun / Mapuche (Chile & Argentina)', nativeName: 'Mapudungun', flag: '🇨🇱', region: 'Americas' },
  { code: 'guc-CO', name: 'Wayuu / Wayuunaiki (Colombia & Venezuela)', nativeName: 'Wayuunaiki', flag: '🇨🇴', region: 'Americas' },
  { code: 'emb-PA', name: 'Embera (Panama & Colombia)', nativeName: 'Emberá', flag: '🇵🇦', region: 'Americas' },
  { code: 'kna-PA', name: 'Guna / Kuna (Panama)', nativeName: 'Gundule / Dulegaya', flag: '🇵🇦', region: 'Americas' },
  { code: 'misk-NI', name: 'Miskito (Nicaragua & Honduras)', nativeName: 'Mískitu bila', flag: '🇳🇮', region: 'Americas' },
  { code: 'gar-HN', name: 'Garifuna (Honduras / Belize / Guatemala)', nativeName: 'Garifuna', flag: '🇭🇳', region: 'Americas' },
  { code: 'ht-HT', name: 'Haitian Creole (Haiti)', nativeName: 'Kreyòl Ayisyen', flag: '🇭🇹', region: 'Caribbean' },
  { code: 'jam-JM', name: 'Jamaican Patois (Jamaica)', nativeName: 'Patwa / Jumiekan', flag: '🇯🇲', region: 'Caribbean' },
  { code: 'pap-AW', name: 'Papiamento (Aruba & Bonaire)', nativeName: 'Papiamento (Aruba)', flag: '🇦🇼', region: 'Caribbean' },
  { code: 'pap-CW', name: 'Papiamentu (Curaçao)', nativeName: 'Papiamentu (Kòrsou)', flag: '🇨🇼', region: 'Caribbean' },
  { code: 'srn-SR', name: 'Sranan Tongo (Suriname)', nativeName: 'Sranantongo', flag: '🇸🇷', region: 'Americas' },
  { code: 'gcr-GF', name: 'French Guianese Creole (French Guiana)', nativeName: 'Kriyòl Gwiyannen', flag: '🇬🇫', region: 'Americas' },
  { code: 'gcf-GP', name: 'Guadeloupean Creole (Guadeloupe)', nativeName: 'Kréyòl Gwadloupéyen', flag: '🇬🇵', region: 'Caribbean' },
  { code: 'gcf-MQ', name: 'Martinican Creole (Martinique)', nativeName: 'Kréyòl Matinitjé', flag: '🇲🇶', region: 'Caribbean' },

  // ==========================================
  // OCEANIA & PACIFIC ISLAND LANGUAGES
  // ==========================================
  { code: 'mi-NZ', name: 'Māori (New Zealand)', nativeName: 'Te Reo Māori', flag: '🇳🇿', region: 'Oceania' },
  { code: 'sm-WS', name: 'Samoan (Samoa & American Samoa)', nativeName: 'Gagana Samoa', flag: '🇼🇸', region: 'Oceania' },
  { code: 'to-TO', name: 'Tongan (Tonga)', nativeName: 'Lea Faka-Tonga', flag: '🇹🇴', region: 'Oceania' },
  { code: 'fj-FJ', name: 'Fijian (Fiji)', nativeName: 'Na Vosa Vakaviti', flag: '🇫🇯', region: 'Oceania' },
  { code: 'hif-FJ', name: 'Fiji Hindi (Fiji)', nativeName: 'फ़िजी बात / Fiji Baat', flag: '🇫🇯', region: 'Oceania' },
  { code: 'ty-PF', name: 'Tahitian (French Polynesia)', nativeName: 'Reo Tahiti', flag: '🇵🇫', region: 'Oceania' },
  { code: 'haw-US', name: 'Hawaiian (Hawaii / USA)', nativeName: 'ʻŌlelo Hawaiʻi', flag: '🇺🇸', region: 'Oceania' },
  { code: 'tpi-PG', name: 'Tok Pisin (Papua New Guinea)', nativeName: 'Tok Pisin', flag: '🇵🇬', region: 'Oceania' },
  { code: 'hmo-PG', name: 'Hiri Motu (Papua New Guinea)', nativeName: 'Hiri Motu', flag: '🇵🇬', region: 'Oceania' },
  { code: 'bi-VU', name: 'Bislama (Vanuatu)', nativeName: 'Bislama', flag: '🇻🇺', region: 'Oceania' },
  { code: 'ch-GU', name: 'Chamorro (Guam & Northern Marianas)', nativeName: 'Finu\' Chamoru', flag: '🇬🇺', region: 'Oceania' },
  { code: 'pau-PW', name: 'Palauan (Palau)', nativeName: 'Tekoi er a Belau', flag: '🇵🇼', region: 'Oceania' },
  { code: 'mh-MH', name: 'Marshallese (Marshall Islands)', nativeName: 'Kajin M̧ajeļ', flag: '🇲🇭', region: 'Oceania' },
  { code: 'gil-KI', name: 'Gilbertese / Kiribati (Kiribati)', nativeName: 'Taetae ni Kiribati', flag: '🇰🇮', region: 'Oceania' },
  { code: 'tvl-TV', name: 'Tuvaluan (Tuvalu)', nativeName: 'Te Gagana Tuvalu', flag: '🇹🇻', region: 'Oceania' },
  { code: 'nau-NR', name: 'Nauruan (Nauru)', nativeName: 'Dorerin Naoero', flag: '🇳🇷', region: 'Oceania' },
  { code: 'rar-CK', name: 'Cook Islands Māori / Rarotongan', nativeName: 'Māori Kūki \'Āirani', flag: '🇨🇰', region: 'Oceania' },
  { code: 'niu-NU', name: 'Niuean (Niue)', nativeName: 'Vagahau Niue', flag: '🇳🇺', region: 'Oceania' },
  { code: 'rap-CL', name: 'Rapa Nui (Easter Island / Chile)', nativeName: 'Vananga Rapa Nui', flag: '🇨🇱', region: 'Oceania' },
  { code: 'pon-FM', name: 'Pohnpeian (Micronesia)', nativeName: 'Mahsen en Pohnpei', flag: '🇫🇲', region: 'Oceania' },
  { code: 'chk-FM', name: 'Chuukese (Micronesia)', nativeName: 'Fosun Chuuk', flag: '🇫🇲', region: 'Oceania' },
  { code: 'yap-FM', name: 'Yapese (Micronesia)', nativeName: 'Thin nu Wa\'ab', flag: '🇫🇲', region: 'Oceania' },
  { code: 'kos-FM', name: 'Kosraean (Micronesia)', nativeName: 'Mahs Kusaie', flag: '🇫🇲', region: 'Oceania' },

  // ==========================================
  // CONSTRUCTED & CLASSICAL LANGUAGES
  // ==========================================
  { code: 'eo', name: 'Esperanto (International)', nativeName: 'Esperanto', flag: '🟢', region: 'International' },
  { code: 'ia', name: 'Interlingua', nativeName: 'Interlingua', flag: '🌐', region: 'International' },
  { code: 'la', name: 'Latin (Classical)', nativeName: 'Lingua Latina', flag: '🇻🇦', region: 'Classical' },
  { code: 'grc', name: 'Ancient Greek', nativeName: 'Ἀρχαία Ἑλληνική', flag: '🏛️', region: 'Classical' },
  { code: 'ang', name: 'Old English / Anglo-Saxon', nativeName: 'Ænglisc', flag: '📜', region: 'Historical' },
  { code: 'non', name: 'Old Norse / Viking', nativeName: 'Dǫnsk tunga', flag: '⚔️', region: 'Historical' },
];

// Additional Regional Variants to ensure 520+ distinct locales
export const ALL_WORLD_LANGUAGES: CountryLanguage[] = [
  ...COMPREHENSIVE_WORLD_LANGUAGES,
  // Detailed African local dialects
  { code: 'kri-SL', name: 'Krio (Sierra Leone)', nativeName: 'Krio', flag: '🇸🇱', region: 'Africa' },
  { code: 'men-SL', name: 'Mende (Sierra Leone)', nativeName: 'Mɛnde yia', flag: '🇸🇱', region: 'Africa' },
  { code: 'tem-SL', name: 'Temne (Sierra Leone)', nativeName: 'Kətʰɛmnɛ', flag: '🇸🇱', region: 'Africa' },
  { code: 'lib-LR', name: 'Liberian Kreyol English', nativeName: 'Kolokwa / Liberian Pidgin', flag: '🇱🇷', region: 'Africa' },
  { code: 'kru-LR', name: 'Kru / Bassa (Liberia)', nativeName: 'Bassa', flag: '🇱🇷', region: 'Africa' },
  { code: 'kpe-LR', name: 'Kpelle (Liberia & Guinea)', nativeName: 'Kpɛlɛwoo', flag: '🇱🇷', region: 'Africa' },
  { code: 'sus-GN', name: 'Susu (Guinea & Sierra Leone)', nativeName: 'Sosoxui', flag: '🇬🇳', region: 'Africa' },
  { code: 'kis-GN', name: 'Kissi (Guinea)', nativeName: 'Kizize', flag: '🇬🇳', region: 'Africa' },
  { code: 'toma-GN', name: 'Loma / Toma (Guinea & Liberia)', nativeName: 'Löömágìtì', flag: '🇬🇳', region: 'Africa' },
  { code: 'son-ML', name: 'Songhay / Koyraboro Senni (Mali)', nativeName: 'Koyraboro Senni', flag: '🇲🇱', region: 'Africa' },
  { code: 'tmh-ML', name: 'Tadaksahak (Mali)', nativeName: 'Tadaksahak', flag: '🇲🇱', region: 'Africa' },
  { code: 'dgo-ML', name: 'Dogon (Mali)', nativeName: 'Dogooso', flag: '🇲🇱', region: 'Africa' },
  { code: 'snk-ML', name: 'Soninke (Mali & Senegal & Mauritania)', nativeName: 'Sooninkanxanne', flag: '🇲🇱', region: 'Africa' },
  { code: 'ser-SN', name: 'Serer (Senegal & Gambia)', nativeName: 'Seereer', flag: '🇸🇳', region: 'Africa' },
  { code: 'dyo-SN', name: 'Jola-Fonyi / Diola (Senegal)', nativeName: 'Jóola Fóoñi', flag: '🇸🇳', region: 'Africa' },
  { code: 'bal-SN', name: 'Balanta (Guinea-Bissau & Senegal)', nativeName: 'Balanta', flag: '🇬🇼', region: 'Africa' },
  { code: 'man-GW', name: 'Mandjak (Guinea-Bissau)', nativeName: 'Manjaku', flag: '🇬🇼', region: 'Africa' },
  { code: 'pap-GW', name: 'Papel (Guinea-Bissau)', nativeName: 'Pepel', flag: '🇬🇼', region: 'Africa' },
  { code: 'gur-BF', name: 'Frafra / Gurune (Ghana & Burkina Faso)', nativeName: 'Gurenɛ', flag: '🇧🇫', region: 'Africa' },
  { code: 'bwa-BF', name: 'Bwamu / Bwa (Burkina Faso)', nativeName: 'Bwamu', flag: '🇧🇫', region: 'Africa' },
  { code: 'dga-GH', name: 'Dagaare (Ghana & Burkina Faso)', nativeName: 'Dagaare', flag: '🇬🇭', region: 'Africa' },
  { code: 'kwa-GH', name: 'Kwahu (Ghana)', nativeName: 'Kwahu Twi', flag: '🇬🇭', region: 'Africa' },
  { code: 'aku-GH', name: 'Akuapem (Ghana)', nativeName: 'Akuapem Twi', flag: '🇬🇭', region: 'Africa' },
  { code: 'asa-GH', name: 'Asante (Ghana)', nativeName: 'Asante Twi', flag: '🇬🇭', region: 'Africa' },
  { code: 'kru-CI', name: 'Bété (Côte d’Ivoire)', nativeName: 'Bété', flag: '🇨🇮', region: 'Africa' },
  { code: 'sen-CI', name: 'Senufo (Côte d’Ivoire & Mali)', nativeName: 'Sénoufo', flag: '🇨🇮', region: 'Africa' },
  { code: 'dan-CI', name: 'Dan / Yacouba (Côte d’Ivoire)', nativeName: 'Dan / Yacouba', flag: '🇨🇮', region: 'Africa' },
  { code: 'any-CI', name: 'Anyi (Côte d’Ivoire & Ghana)', nativeName: 'Anyin', flag: '🇨🇮', region: 'Africa' },
  { code: 'gun-BJ', name: 'Gun / Gungbe (Benin & Nigeria)', nativeName: 'Gungbe', flag: '🇧🇯', region: 'Africa' },
  { code: 'bar-BJ', name: 'Bariba / Baatombu (Benin)', nativeName: 'Baatɔnum', flag: '🇧🇯', region: 'Africa' },
  { code: 'dit-BJ', name: 'Ditamari (Benin)', nativeName: 'Ditammari', flag: '🇧🇯', region: 'Africa' },
  { code: 'tem-TG', name: 'Kotokoli / Tem (Togo)', nativeName: 'Tem', flag: '🇹🇬', region: 'Africa' },
  { code: 'mob-TG', name: 'Moba (Togo & Ghana)', nativeName: 'Moba', flag: '🇹🇬', region: 'Africa' },
  { code: 'zar-NE', name: 'Zarma / Djerma (Niger)', nativeName: 'Zarmaciine', flag: '🇳🇪', region: 'Africa' },
  { code: 'kan-NE', name: 'Kanuri (Niger & Nigeria & Chad)', nativeName: 'Kanuri', flag: '🇳🇪', region: 'Africa' },
  { code: 'tbu-NE', name: 'Tubu / Tedaga (Niger & Chad & Libya)', nativeName: 'Tedaga', flag: '🇳🇪', region: 'Africa' },
  { code: 'shu-TD', name: 'Chadian Arabic / Shuwa (Chad)', nativeName: 'لهجة تشادية', flag: '🇹🇩', region: 'Africa', rtl: true },
  { code: 'sar-TD', name: 'Sara (Chad)', nativeName: 'Ngambay / Sara', flag: '🇹🇩', region: 'Africa' },
  { code: 'mbb-TD', name: 'Maba (Chad & Sudan)', nativeName: 'Maba', flag: '🇹🇩', region: 'Africa' },
  { code: 'gaw-CM', name: 'Ghomala\' (Cameroon)', nativeName: 'Ghomálá’', flag: '🇨🇲', region: 'Africa' },
  { code: 'baf-CM', name: 'Bassa (Cameroon)', nativeName: 'Mbene / Bassa', flag: '🇨🇲', region: 'Africa' },
  { code: 'ful-CM', name: 'Adamawa Fulfulde (Cameroon)', nativeName: 'Fulfulde Adamawa', flag: '🇨🇲', region: 'Africa' },
  { code: 'byv-CM', name: 'Medumba (Cameroon)', nativeName: 'Mədʉ̂mbɑ', flag: '🇨🇲', region: 'Africa' },
  { code: 'bax-CM', name: 'Bamun (Cameroon)', nativeName: 'Shüpamom', flag: '🇨🇲', region: 'Africa' },
  { code: 'myb-GA', name: 'Myene (Gabon)', nativeName: 'Omyènè', flag: '🇬🇦', region: 'Africa' },
  { code: 'pnz-GA', name: 'Punu (Gabon)', nativeName: 'Yipunu', flag: '🇬🇦', region: 'Africa' },
  { code: 'tek-CG', name: 'Teke (Republic of the Congo)', nativeName: 'Kiteke', flag: '🇨🇬', region: 'Africa' },
  { code: 'mbo-CG', name: 'Mbochi (Republic of the Congo)', nativeName: 'Mbochi', flag: '🇨🇬', region: 'Africa' },
  { code: 'mon-CD', name: 'Mongo (DR Congo)', nativeName: 'Lomongo', flag: '🇨🇩', region: 'Africa' },
  { code: 'tet-CD', name: 'Tetela (DR Congo)', nativeName: 'Otetela', flag: '🇨🇩', region: 'Africa' },
  { code: 'ngb-CD', name: 'Ngbandi (DR Congo & CAR)', nativeName: 'Ngbandi', flag: '🇨🇩', region: 'Africa' },
  { code: 'lba-CD', name: 'Luba-Katanga (DR Congo)', nativeName: 'Kiluba', flag: '🇨🇩', region: 'Africa' },
  { code: 'znd-CD', name: 'Zande (DR Congo & South Sudan)', nativeName: 'Pazande', flag: '🇨🇩', region: 'Africa' },
  { code: 'nku-AO', name: 'Nkumbi (Angola)', nativeName: 'Nkumbi', flag: '🇦🇴', region: 'Africa' },
  { code: 'cjo-AO', name: 'Chokwe (Angola & DR Congo)', nativeName: 'Cokwe', flag: '🇦🇴', region: 'Africa' },
  { code: 'kwn-NA', name: 'Kwangali / Rukwangali (Namibia)', nativeName: 'Rukwangali', flag: '🇳🇦', region: 'Africa' },
  { code: 'khi-NA', name: 'Khoekhoe / Nama (Namibia)', nativeName: 'Khoekhoegowab', flag: '🇳🇦', region: 'Africa' },
  { code: 'her-NA', name: 'Herero / Otjiherero (Namibia)', nativeName: 'Otjiherero', flag: '🇳🇦', region: 'Africa' },
  { code: 'osh-NA', name: 'Oshiwambo / Oshindonga (Namibia & Angola)', nativeName: 'Oshiwambo', flag: '🇳🇦', region: 'Africa' },
  { code: 'kua-NA', name: 'Kwanyama (Namibia & Angola)', nativeName: 'Oshikwanyama', flag: '🇳🇦', region: 'Africa' },
  { code: 'kgl-BW', name: 'Kgalagadi (Botswana)', nativeName: 'SheKgalagadi', flag: '🇧🇼', region: 'Africa' },
  { code: 'nhe-ZW', name: 'Manyika (Zimbabwe)', nativeName: 'chiManyika', flag: '🇿🇼', region: 'Africa' },
  { code: 'kzn-ZW', name: 'Karanga (Zimbabwe)', nativeName: 'chiKaranga', flag: '🇿🇼', region: 'Africa' },
  { code: 'zre-ZW', name: 'Zezuru (Zimbabwe)', nativeName: 'chiZezuru', flag: '🇿🇼', region: 'Africa' },
  { code: 'tum-MW', name: 'Tumbuka (Malawi & Zambia)', nativeName: 'chiTumbuka', flag: '🇲🇼', region: 'Africa' },
  { code: 'yao-MW', name: 'Yao / Chiyao (Malawi & Mozambique & Tanzania)', nativeName: 'Chiyao', flag: '🇲🇼', region: 'Africa' },
  { code: 'lom-MZ', name: 'Lomwe (Mozambique & Malawi)', nativeName: 'Elomwe', flag: '🇲🇿', region: 'Africa' },
  { code: 'cho-MZ', name: 'Chopi (Mozambique)', nativeName: 'Cicopi', flag: '🇲🇿', region: 'Africa' },
  { code: 'ron-MZ', name: 'Ronga (Mozambique)', nativeName: 'Xironga', flag: '🇲🇿', region: 'Africa' },
  { code: 'sid-ET', name: 'Sidamo (Ethiopia)', nativeName: 'Sidaamu Afoo', flag: '🇪🇹', region: 'Africa' },
  { code: 'wal-ET', name: 'Wolaytta (Ethiopia)', nativeName: 'Wolaitta', flag: '🇪🇹', region: 'Africa' },
  { code: 'gur-ET', name: 'Gurage (Ethiopia)', nativeName: 'ጉራጊኛ', flag: '🇪🇹', region: 'Africa' },
  { code: 'had-ET', name: 'Hadiya (Ethiopia)', nativeName: 'Hadiyisa', flag: '🇪🇹', region: 'Africa' },
  { code: 'gam-ET', name: 'Gamo (Ethiopia)', nativeName: 'Gamo', flag: '🇪🇹', region: 'Africa' },
  { code: 'tig-ER', name: 'Tigre (Eritrea & Sudan)', nativeName: 'ትግሬ / خاصية', flag: '🇪🇷', region: 'Africa' },
  { code: 'bln-ER', name: 'Bilen (Eritrea)', nativeName: 'ብሊን', flag: '🇪🇷', region: 'Africa' },
  { code: 'kun-ER', name: 'Kunama (Eritrea & Ethiopia)', nativeName: 'Kunama', flag: '🇪🇷', region: 'Africa' },
  { code: 'nba-ER', name: 'Nara (Eritrea)', nativeName: 'Nara', flag: '🇪🇷', region: 'Africa' },
  { code: 'bej-SD', name: 'Beja (Sudan & Egypt & Eritrea)', nativeName: 'Bidhaawyeet', flag: '🇸🇩', region: 'Africa' },
  { code: 'fur-SD', name: 'Fur (Darfur / Sudan)', nativeName: 'bèle fòòr', flag: '🇸🇩', region: 'Africa' },
  { code: 'mas-SD', name: 'Masalit (Darfur / Sudan & Chad)', nativeName: 'Kaana Masala', flag: '🇸🇩', region: 'Africa' },
  { code: 'nob-SD', name: 'Nobiin / Nubian (Sudan & Egypt)', nativeName: 'Nòbîin', flag: '🇸🇩', region: 'Africa' },
  { code: 'bari-SS', name: 'Bari (South Sudan & Uganda)', nativeName: 'Kutuk na Bari', flag: '🇸🇸', region: 'Africa' },
  { code: 'lot-SS', name: 'Otuho / Lotuko (South Sudan)', nativeName: 'Otuho', flag: '🇸🇸', region: 'Africa' },
  { code: 'top-SS', name: 'Toposa (South Sudan)', nativeName: 'Topotha', flag: '🇸🇸', region: 'Africa' },
  { code: 'zaz-TR', name: 'Zaza / Zazaki (Turkey)', nativeName: 'Zazaki / Dımli', flag: '🇹🇷', region: 'Middle East' },
  { code: 'laz-TR', name: 'Laz (Turkey & Georgia)', nativeName: 'Lazuri / ლაზური', flag: '🇹🇷', region: 'Caucasus' },
  { code: 'lad-IL', name: 'Ladino / Judeo-Spanish (Israel & Turkey)', nativeName: 'Djudeo-espanyol', flag: '🇮🇱', region: 'Middle East' },
  { code: 'yi-IL', name: 'Yiddish (Israel & Americas & Europe)', nativeName: 'ייִדיש', flag: '🇮🇱', region: 'International', rtl: true },
  { code: 'jpa-IL', name: 'Judeo-Arabic (Israel & Middle East)', nativeName: 'ערבית יהודית', flag: '🇮🇱', region: 'Middle East', rtl: true },
  { code: 'tly-AZ', name: 'Talysh (Azerbaijan & Iran)', nativeName: 'Tolışi', flag: '🇦🇿', region: 'Caucasus' },
  { code: 'lez-RU', name: 'Lezgian (Dagestan & Azerbaijan)', nativeName: 'Лезги чIал', flag: '🇷🇺', region: 'Caucasus' },
  { code: 'dar-RU', name: 'Dargwa (Dagestan)', nativeName: 'Дарган мез', flag: '🇷🇺', region: 'Caucasus' },
  { code: 'lak-RU', name: 'Lak (Dagestan)', nativeName: 'Лакку маз', flag: '🇷🇺', region: 'Caucasus' },
  { code: 'inh-RU', name: 'Ingush (Ingushetia / Russia)', nativeName: 'Гӏалгӏай мотт', flag: '🇷🇺', region: 'Caucasus' },
  { code: 'krc-RU', name: 'Karachay-Balkar (Caucasus)', nativeName: 'Къарачай-малкъар тил', flag: '🇷🇺', region: 'Caucasus' },
  { code: 'kbd-RU', name: 'Kabardian / Circassian (Caucasus)', nativeName: 'Адыгэбзэ (Къэбэрдей)', flag: '🇷🇺', region: 'Caucasus' },
  { code: 'ady-RU', name: 'Adyghe / West Circassian (Caucasus)', nativeName: 'Адыгабзэ', flag: '🇷🇺', region: 'Caucasus' },
  { code: 'ab-GE', name: 'Abkhazian (Abkhazia / Georgia)', nativeName: 'Аҧсуа бызшәа', flag: '🇬🇪', region: 'Caucasus' },
  { code: 'sva-GE', name: 'Svan (Georgia)', nativeName: 'ლუშნუ ნინ', flag: '🇬🇪', region: 'Caucasus' },
  { code: 'xmf-GE', name: 'Mingrelian (Georgia)', nativeName: 'მარგალური ნინა', flag: '🇬🇪', region: 'Caucasus' },
  { code: 'chm-RU', name: 'Mari / Meadow Mari (Russia)', nativeName: 'Марий йылме', flag: '🇷🇺', region: 'Europe / Asia' },
  { code: 'udm-RU', name: 'Udmurt (Russia)', nativeName: 'Удмурт кыл', flag: '🇷🇺', region: 'Europe / Asia' },
  { code: 'kpv-RU', name: 'Komi (Russia)', nativeName: 'Коми кыв', flag: '🇷🇺', region: 'Europe / Asia' },
  { code: 'myv-RU', name: 'Erzya (Mordovia / Russia)', nativeName: 'Эрзянь кель', flag: '🇷🇺', region: 'Europe / Asia' },
  { code: 'mdf-RU', name: 'Moksha (Mordovia / Russia)', nativeName: 'Мокшень кяль', flag: '🇷🇺', region: 'Europe / Asia' },
  { code: 'kal-RU', name: 'Kalmyk Oirat (Kalmykia / Russia)', nativeName: 'Хальмг келн', flag: '🇷🇺', region: 'Europe / Asia' },
  { code: 'bua-RU', name: 'Buryat (Siberia / Russia)', nativeName: 'Буряад хэлэн', flag: '🇷🇺', region: 'Asia' },
  { code: 'alt-RU', name: 'Altai (Altai Republic / Russia)', nativeName: 'Алтай тил', flag: '🇷🇺', region: 'Asia' },
  { code: 'khk-RU', name: 'Khakas (Khakassia / Russia)', nativeName: 'Хакас тілі', flag: '🇷🇺', region: 'Asia' },
  { code: 'eve-RU', name: 'Evenki (Siberia / Russia & China)', nativeName: 'Эведы̄ турэ̄н', flag: '🇷🇺', region: 'Asia' },
  { code: 'ckt-RU', name: 'Chukchi (Chukotka / Russia)', nativeName: 'Ԓыгъоравэтԓьэн йилыйиstate', flag: '🇷🇺', region: 'Asia' },
  { code: 'kory-RU', name: 'Koryak (Kamchatka / Russia)', nativeName: 'Нымылан', flag: '🇷🇺', region: 'Asia' },
  { code: 'niv-RU', name: 'Nivkh / Gilyak (Sakhalin / Russia)', nativeName: 'Нивх диф', flag: '🇷🇺', region: 'Asia' },
  { code: 'ain-JP', name: 'Ainu (Hokkaido / Japan)', nativeName: 'アイヌ・イタㇰ', flag: '🇯🇵', region: 'Asia' },
  { code: 'ryu-JP', name: 'Okinawan / Uchinaaguchi (Ryukyu / Japan)', nativeName: '沖縄口 / うちなぁぐち', flag: '🇯🇵', region: 'Asia' },
  { code: 'mvi-JP', name: 'Miyako (Ryukyu / Japan)', nativeName: 'ミャークフツ', flag: '🇯🇵', region: 'Asia' },
  { code: 'yoi-JP', name: 'Yonaguni (Ryukyu / Japan)', nativeName: 'ドゥナンちまぶち', flag: '🇯🇵', region: 'Asia' },
  { code: 'jeju-KR', name: 'Jeju / Jejueo (Jeju Island / South Korea)', nativeName: '제주말 / 제줏말', flag: '🇰🇷', region: 'Asia' },
  { code: 'tai-TW', name: 'Taiwanese Indigenous / Amis (Taiwan)', nativeName: 'Pangcah / \'Amis', flag: '🇹🇼', region: 'Asia' },
  { code: 'atn-TW', name: 'Atayal (Taiwan)', nativeName: 'Kagang Atayal', flag: '🇹🇼', region: 'Asia' },
  { code: 'pai-TW', name: 'Paiwan (Taiwan)', nativeName: 'Pinayuanan', flag: '🇹🇼', region: 'Asia' },
  { code: 'bun-TW', name: 'Bunun (Taiwan)', nativeName: 'Bunun', flag: '🇹🇼', region: 'Asia' },
  { code: 'trv-TW', name: 'Seediq / Truku (Taiwan)', nativeName: 'Kari Seediq', flag: '🇹🇼', region: 'Asia' },
  { code: 'pwn-TW', name: 'Puyuma (Taiwan)', nativeName: 'Pinuyumayan', flag: '🇹🇼', region: 'Asia' },
  { code: 'tao-TW', name: 'Tao / Yami (Orchid Island / Taiwan)', nativeName: 'Ciriciring no Tao', flag: '🇹🇼', region: 'Asia' },
  { code: 'tsu-TW', name: 'Tsou (Taiwan)', nativeName: 'Cou', flag: '🇹🇼', region: 'Asia' },
  { code: 'sais-TW', name: 'Saisiyat (Taiwan)', nativeName: 'SaySiyat', flag: '🇹🇼', region: 'Asia' },
  { code: 'kav-TW', name: 'Kavalan (Taiwan)', nativeName: 'Kebalan', flag: '🇹🇼', region: 'Asia' },
  { code: 'thao-TW', name: 'Thao (Sun Moon Lake / Taiwan)', nativeName: 'Thaw a ka parhawan', flag: '🇹🇼', region: 'Asia' },
  { code: 'ruk-TW', name: 'Rukai (Taiwan)', nativeName: 'Drekay', flag: '🇹🇼', region: 'Asia' },
  { code: 'sax-TW', name: 'Sakizaya (Taiwan)', nativeName: 'Sakizaya', flag: '🇹🇼', region: 'Asia' },
  { code: 'hla-TW', name: 'Hla\'alua / Saaroa (Taiwan)', nativeName: 'Hla\'alua', flag: '🇹🇼', region: 'Asia' },
  { code: 'kan-TW', name: 'Kanakanavu (Taiwan)', nativeName: 'Kanakanavu', flag: '🇹🇼', region: 'Asia' },

  // ==========================================
  // EXTENSIVE GLOBAL COUNTRY VARIANTS & DIALECTS (500+ COLLECTION)
  // ==========================================
  // English Worldwide Variants
  { code: 'en-AG', name: 'English (Antigua & Barbuda)', nativeName: 'English (Antigua)', flag: '🇦🇬', region: 'Caribbean' },
  { code: 'en-DM', name: 'English (Dominica)', nativeName: 'English (Dominica)', flag: '🇩🇲', region: 'Caribbean' },
  { code: 'en-GD', name: 'English (Grenada)', nativeName: 'English (Grenada)', flag: '🇬🇩', region: 'Caribbean' },
  { code: 'en-KN', name: 'English (Saint Kitts & Nevis)', nativeName: 'English (St. Kitts)', flag: '🇰🇳', region: 'Caribbean' },
  { code: 'en-LC', name: 'English (Saint Lucia)', nativeName: 'English (St. Lucia)', flag: '🇱🇨', region: 'Caribbean' },
  { code: 'en-VC', name: 'English (Saint Vincent & Grenadines)', nativeName: 'English (St. Vincent)', flag: '🇻🇨', region: 'Caribbean' },
  { code: 'en-AI', name: 'English (Anguilla)', nativeName: 'English (Anguilla)', flag: '🇦🇮', region: 'Caribbean' },
  { code: 'en-BM', name: 'English (Bermuda)', nativeName: 'English (Bermuda)', flag: '🇧🇲', region: 'Caribbean' },
  { code: 'en-KY', name: 'English (Cayman Islands)', nativeName: 'English (Cayman)', flag: '🇰🇾', region: 'Caribbean' },
  { code: 'en-MS', name: 'English (Montserrat)', nativeName: 'English (Montserrat)', flag: '🇲🇸', region: 'Caribbean' },
  { code: 'en-TC', name: 'English (Turks & Caicos)', nativeName: 'English (Turks & Caicos)', flag: '🇹🇨', region: 'Caribbean' },
  { code: 'en-VG', name: 'English (British Virgin Islands)', nativeName: 'English (BVI)', flag: '🇻🇬', region: 'Caribbean' },
  { code: 'en-VI', name: 'English (US Virgin Islands)', nativeName: 'English (USVI)', flag: '🇻🇮', region: 'Caribbean' },
  { code: 'en-GI', name: 'English (Gibraltar)', nativeName: 'English (Gibraltar)', flag: '🇬🇮', region: 'Europe' },
  { code: 'en-BW', name: 'English (Botswana)', nativeName: 'English (Botswana)', flag: '🇧🇼', region: 'Africa' },
  { code: 'en-CM', name: 'English (Cameroon)', nativeName: 'English (Cameroon)', flag: '🇨🇲', region: 'Africa' },
  { code: 'en-ET', name: 'English (Ethiopia)', nativeName: 'English (Ethiopia)', flag: '🇪🇹', region: 'Africa' },
  { code: 'en-GM', name: 'English (Gambia)', nativeName: 'English (Gambia)', flag: '🇬🇲', region: 'Africa' },
  { code: 'en-LR', name: 'English (Liberia)', nativeName: 'English (Liberia)', flag: '🇱🇷', region: 'Africa' },
  { code: 'en-MW', name: 'English (Malawi)', nativeName: 'English (Malawi)', flag: '🇲🇼', region: 'Africa' },
  { code: 'en-MU', name: 'English (Mauritius)', nativeName: 'English (Mauritius)', flag: '🇲🇺', region: 'Africa' },
  { code: 'en-NA', name: 'English (Namibia)', nativeName: 'English (Namibia)', flag: '🇳🇦', region: 'Africa' },
  { code: 'en-RW', name: 'English (Rwanda)', nativeName: 'English (Rwanda)', flag: '🇷🇼', region: 'Africa' },
  { code: 'en-SC', name: 'English (Seychelles)', nativeName: 'English (Seychelles)', flag: '🇸🇨', region: 'Africa' },
  { code: 'en-SL', name: 'English (Sierra Leone)', nativeName: 'English (Sierra Leone)', flag: '🇸🇱', region: 'Africa' },
  { code: 'en-SS', name: 'English (South Sudan)', nativeName: 'English (South Sudan)', flag: '🇸🇸', region: 'Africa' },
  { code: 'en-SZ', name: 'English (Eswatini)', nativeName: 'English (Eswatini)', flag: '🇸🇿', region: 'Africa' },
  { code: 'en-TZ', name: 'English (Tanzania)', nativeName: 'English (Tanzania)', flag: '🇹🇿', region: 'Africa' },
  { code: 'en-UG', name: 'English (Uganda)', nativeName: 'English (Uganda)', flag: '🇺🇬', region: 'Africa' },
  { code: 'en-ZM', name: 'English (Zambia)', nativeName: 'English (Zambia)', flag: '🇿🇲', region: 'Africa' },
  { code: 'en-ZW', name: 'English (Zimbabwe)', nativeName: 'English (Zimbabwe)', flag: '🇿🇼', region: 'Africa' },
  { code: 'en-FJ', name: 'English (Fiji)', nativeName: 'English (Fiji)', flag: '🇫🇯', region: 'Oceania' },
  { code: 'en-GU', name: 'English (Guam)', nativeName: 'English (Guam)', flag: '🇬🇺', region: 'Oceania' },
  { code: 'en-KI', name: 'English (Kiribati)', nativeName: 'English (Kiribati)', flag: '🇰🇮', region: 'Oceania' },
  { code: 'en-MH', name: 'English (Marshall Islands)', nativeName: 'English (Marshall Islands)', flag: '🇲🇭', region: 'Oceania' },
  { code: 'en-FM', name: 'English (Micronesia)', nativeName: 'English (Micronesia)', flag: '🇫🇲', region: 'Oceania' },
  { code: 'en-NR', name: 'English (Nauru)', nativeName: 'English (Nauru)', flag: '🇳🇷', region: 'Oceania' },
  { code: 'en-MP', name: 'English (Northern Mariana Islands)', nativeName: 'English (Marianas)', flag: '🇲🇵', region: 'Oceania' },
  { code: 'en-PW', name: 'English (Palau)', nativeName: 'English (Palau)', flag: '🇵🇼', region: 'Oceania' },
  { code: 'en-PG', name: 'English (Papua New Guinea)', nativeName: 'English (PNG)', flag: '🇵🇬', region: 'Oceania' },
  { code: 'en-WS', name: 'English (Samoa)', nativeName: 'English (Samoa)', flag: '🇼🇸', region: 'Oceania' },
  { code: 'en-SB', name: 'English (Solomon Islands)', nativeName: 'English (Solomon Islands)', flag: '🇸🇧', region: 'Oceania' },
  { code: 'en-TO', name: 'English (Tonga)', nativeName: 'English (Tonga)', flag: '🇹🇴', region: 'Oceania' },
  { code: 'en-TV', name: 'English (Tuvalu)', nativeName: 'English (Tuvalu)', flag: '🇹🇻', region: 'Oceania' },
  { code: 'en-VU', name: 'English (Vanuatu)', nativeName: 'English (Vanuatu)', flag: '🇻🇺', region: 'Oceania' },
  { code: 'en-HK', name: 'English (Hong Kong)', nativeName: 'English (Hong Kong)', flag: '🇭🇰', region: 'Asia' },
  { code: 'en-PK', name: 'English (Pakistan)', nativeName: 'English (Pakistan)', flag: '🇵🇰', region: 'Asia' },
  { code: 'en-MY', name: 'English (Malaysia)', nativeName: 'English (Malaysia)', flag: '🇲🇾', region: 'Asia' },

  // French Worldwide Variants
  { code: 'fr-BI', name: 'French (Burundi)', nativeName: 'Français (Burundi)', flag: '🇧🇮', region: 'Africa' },
  { code: 'fr-KM', name: 'French (Comoros)', nativeName: 'Français (Comores)', flag: '🇰🇲', region: 'Africa' },
  { code: 'fr-DJ', name: 'French (Djibouti)', nativeName: 'Français (Djibouti)', flag: '🇩🇯', region: 'Africa' },
  { code: 'fr-GQ', name: 'French (Equatorial Guinea)', nativeName: 'Français (Guinée Équatoriale)', flag: '🇬🇶', region: 'Africa' },
  { code: 'fr-MU', name: 'French (Mauritius)', nativeName: 'Français (Maurice)', flag: '🇲🇺', region: 'Africa' },
  { code: 'fr-SC', name: 'French (Seychelles)', nativeName: 'Français (Seychelles)', flag: '🇸🇨', region: 'Africa' },
  { code: 'fr-TD', name: 'French (Chad)', nativeName: 'Français (Tchad)', flag: '🇹🇩', region: 'Africa' },
  { code: 'fr-CF', name: 'French (Central African Republic)', nativeName: 'Français (Centrafrique)', flag: '🇨🇫', region: 'Africa' },
  { code: 'fr-CG', name: 'French (Congo-Brazzaville)', nativeName: 'Français (Congo)', flag: '🇨🇬', region: 'Africa' },
  { code: 'fr-PF', name: 'French (French Polynesia)', nativeName: 'Français (Polynésie française)', flag: '🇵🇫', region: 'Oceania' },
  { code: 'fr-NC', name: 'French (New Caledonia)', nativeName: 'Français (Nouvelle-Calédonie)', flag: '🇳🇨', region: 'Oceania' },
  { code: 'fr-WF', name: 'French (Wallis & Futuna)', nativeName: 'Français (Wallis-et-Futuna)', flag: '🇼🇫', region: 'Oceania' },
  { code: 'fr-GP', name: 'French (Guadeloupe)', nativeName: 'Français (Guadeloupe)', flag: '🇬🇵', region: 'Caribbean' },
  { code: 'fr-MQ', name: 'French (Martinique)', nativeName: 'Français (Martinique)', flag: '🇲🇶', region: 'Caribbean' },
  { code: 'fr-GF', name: 'French (French Guiana)', nativeName: 'Français (Guyane)', flag: '🇬🇫', region: 'Americas' },
  { code: 'fr-RE', name: 'French (Réunion)', nativeName: 'Français (La Réunion)', flag: '🇷🇪', region: 'Africa' },
  { code: 'fr-YT', name: 'French (Mayotte)', nativeName: 'Français (Mayotte)', flag: '🇾🇹', region: 'Africa' },
  { code: 'fr-PM', name: 'French (Saint Pierre & Miquelon)', nativeName: 'Français (Saint-Pierre)', flag: '🇵🇲', region: 'Americas' },
  { code: 'fr-VU', name: 'French (Vanuatu)', nativeName: 'Français (Vanuatu)', flag: '🇻🇺', region: 'Oceania' },

  // Spanish Worldwide Variants
  { code: 'es-BZ', name: 'Spanish (Belize)', nativeName: 'Español (Belice)', flag: '🇧🇿', region: 'Americas' },
  { code: 'es-US', name: 'Spanish (United States)', nativeName: 'Español (Estados Unidos)', flag: '🇺🇸', region: 'Americas' },
  { code: 'es-PH', name: 'Spanish (Philippines)', nativeName: 'Español de Filipinas', flag: '🇵🇭', region: 'Asia' },
  { code: 'es-GI', name: 'Spanish / Yanito (Gibraltar)', nativeName: 'Llanito / Español de Gibraltar', flag: '🇬🇮', region: 'Europe' },
  { code: 'es-EH', name: 'Spanish (Western Sahara)', nativeName: 'Español (Sáhara Occidental)', flag: '🇪🇭', region: 'Africa' },

  // German Regional Dialects & Worldwide
  { code: 'de-IT', name: 'German (South Tyrol / Italy)', nativeName: 'Deutsch (Südtirol)', flag: '🇮🇹', region: 'Europe' },
  { code: 'de-NA', name: 'German (Namibia)', nativeName: 'Deutsch (Namibia / Südwesterdeutsch)', flag: '🇳🇦', region: 'Africa' },
  { code: 'pdc-US', name: 'Pennsylvania Dutch / German (USA)', nativeName: 'Pennsilfaanisch Deitsch', flag: '🇺🇸', region: 'Americas' },
  { code: 'hrx-BR', name: 'Hunsrik German (Brazil)', nativeName: 'Hunsrik / Riograndenser Hunsrückisch', flag: '🇧🇷', region: 'Americas' },
  { code: 'pom-BR', name: 'Pomeranian German (Brazil)', nativeName: 'Pommersch', flag: '🇧🇷', region: 'Americas' },

  // Italian Dialects & Varieties
  { code: 'egl-IT', name: 'Emilian (Emilia-Romagna / Italy)', nativeName: 'Emiliàn', flag: '🇮🇹', region: 'Europe' },
  { code: 'rgn-IT', name: 'Romagnol (Romagna / Italy)', nativeName: 'Rumagnôl', flag: '🇮🇹', region: 'Europe' },
  { code: 'lij-IT', name: 'Ligurian / Genoese (Liguria / Italy & Monaco)', nativeName: 'Lìgure / Zeneize', flag: '🇮🇹', region: 'Europe' },
  { code: 'tly-IT', name: 'Tuscan (Tuscany / Italy)', nativeName: 'Dialetto toscano', flag: '🇮🇹', region: 'Europe' },
  { code: 'cal-IT', name: 'Calabrian (Calabria / Italy)', nativeName: 'Calabbrisi', flag: '🇮🇹', region: 'Europe' },
  { code: 'sal-IT', name: 'Salentino (Puglia / Italy)', nativeName: 'Salentinu', flag: '🇮🇹', region: 'Europe' },
  { code: 'bar-IT', name: 'Barese (Bari / Italy)', nativeName: 'Barése', flag: '🇮🇹', region: 'Europe' },
  { code: 'it-HR', name: 'Istrian Italian (Croatia & Slovenia)', nativeName: 'Italiano istriano', flag: '🇭🇷', region: 'Europe' },

  // Dutch Caribbean & Sranan Variants
  { code: 'nl-AW', name: 'Dutch (Aruba)', nativeName: 'Nederlands (Aruba)', flag: '🇦🇼', region: 'Caribbean' },
  { code: 'nl-CW', name: 'Dutch (Curaçao)', nativeName: 'Nederlands (Curaçao)', flag: '🇨🇼', region: 'Caribbean' },
  { code: 'nl-SX', name: 'Dutch (Sint Maarten)', nativeName: 'Nederlands (Sint Maarten)', flag: '🇸🇽', region: 'Caribbean' },
  { code: 'nl-BQ', name: 'Dutch (Bonaire, Sint Eustatius & Saba)', nativeName: 'Nederlands (Caribisch Nederland)', flag: '🇧🇶', region: 'Caribbean' },

  // South Asian Himalayan & Regional Tongues
  { code: 'awa-IN', name: 'Awadhi (Uttar Pradesh / India)', nativeName: 'अवधी', flag: '🇮🇳', region: 'Asia' },
  { code: 'bra-IN', name: 'Braj Bhasha (Mathura / India)', nativeName: 'ब्रज भाषा', flag: '🇮🇳', region: 'Asia' },
  { code: 'bnd-IN', name: 'Bundeli (Madhya Pradesh / India)', nativeName: 'बुन्देली', flag: '🇮🇳', region: 'Asia' },
  { code: 'bgq-IN', name: 'Bagheli (Baghelkhand / India)', nativeName: 'बघेली', flag: '🇮🇳', region: 'Asia' },
  { code: 'gbm-IN', name: 'Garhwali (Uttarakhand / India)', nativeName: 'गढ़वळि', flag: '🇮🇳', region: 'Asia' },
  { code: 'kfy-IN', name: 'Kumaoni (Uttarakhand / India)', nativeName: 'कुमाऊँनी', flag: '🇮🇳', region: 'Asia' },
  { code: 'xnr-IN', name: 'Kangri (Himachal Pradesh / India)', nativeName: 'कांगड़ी', flag: '🇮🇳', region: 'Asia' },
  { code: 'kfs-IN', name: 'Kullu Pahari (Himachal Pradesh / India)', nativeName: 'कुलूई', flag: '🇮🇳', region: 'Asia' },
  { code: 'srx-IN', name: 'Sirmauri (Himachal Pradesh / India)', nativeName: 'सिरमौरी', flag: '🇮🇳', region: 'Asia' },
  { code: 'mjl-IN', name: 'Mandeali (Himachal Pradesh / India)', nativeName: 'मण्डयाली', flag: '🇮🇳', region: 'Asia' },
  { code: 'bfz-IN', name: 'Mahasu Pahari (Shimla / India)', nativeName: 'महासू पहाड़ी', flag: '🇮🇳', region: 'Asia' },
  { code: 'wtm-IN', name: 'Mewati (Mewat / India)', nativeName: 'मेवाती', flag: '🇮🇳', region: 'Asia' },
  { code: 'swv-IN', name: 'Shekhawati (Rajasthan / India)', nativeName: 'शेखावाटी', flag: '🇮🇳', region: 'Asia' },
  { code: 'dhd-IN', name: 'Dhundhari / Jaipuri (Rajasthan / India)', nativeName: 'ढूंढाड़ी', flag: '🇮🇳', region: 'Asia' },
  { code: 'hoj-IN', name: 'Harauti / Hadoti (Rajasthan / India)', nativeName: 'हाड़ौती', flag: '🇮🇳', region: 'Asia' },
  { code: 'mup-IN', name: 'Malvi (Madhya Pradesh / India)', nativeName: 'मालवी', flag: '🇮🇳', region: 'Asia' },
  { code: 'noe-IN', name: 'Nimadi (Nimar / India)', nativeName: 'निमाड़ी', flag: '🇮🇳', region: 'Asia' },
  { code: 'bhb-IN', name: 'Bhili (Gujarat & MP & Rajasthan / India)', nativeName: 'भीली', flag: '🇮🇳', region: 'Asia' },
  { code: 'khn-IN', name: 'Khandeshi / Ahirani (Maharashtra / India)', nativeName: 'अहिराणी / खानदेशी', flag: '🇮🇳', region: 'Asia' },
  { code: 'vha-IN', name: 'Varhadi / Vidarbha (Maharashtra / India)', nativeName: 'वऱ्हाडी', flag: '🇮🇳', region: 'Asia' },
  { code: 'hlb-IN', name: 'Halbi (Bastar / Chhattisgarh / India)', nativeName: 'हल्बी', flag: '🇮🇳', region: 'Asia' },
  { code: 'gon-IN', name: 'Gondi (Central India)', nativeName: 'गोंडी / Goindi', flag: '🇮🇳', region: 'Asia' },
  { code: 'kxu-IN', name: 'Kui (Odisha / India)', nativeName: 'କୁଇ / Kui', flag: '🇮🇳', region: 'Asia' },
  { code: 'kxv-IN', name: 'Kuvi (Odisha / India)', nativeName: 'କୁଭି / Kuvi', flag: '🇮🇳', region: 'Asia' },
  { code: 'kru-IN', name: 'Kurukh / Oraon (Jharkhand / India)', nativeName: 'कुड़ुख़ / ᱲᱩᱲᱩᱠᱷ', flag: '🇮🇳', region: 'Asia' },
  { code: 'hoc-IN', name: 'Ho (Jharkhand & Odisha / India)', nativeName: 'ᱦᱳ / Warang Citi', flag: '🇮🇳', region: 'Asia' },
  { code: 'unr-IN', name: 'Mundari (Jharkhand / India)', nativeName: 'मुंडारी / ᱢᱩᱱᱰᱟᱨᱤ', flag: '🇮🇳', region: 'Asia' },
  { code: 'khr-IN', name: 'Kharia (Jharkhand & Odisha / India)', nativeName: 'खड़िया', flag: '🇮🇳', region: 'Asia' },
  { code: 'sck-IN', name: 'Sadri / Nagpuri (Jharkhand / India)', nativeName: 'सादरी / नागपुरी', flag: '🇮🇳', region: 'Asia' },
  { code: 'kyw-IN', name: 'Kurmali / Kudmali (Jharkhand & Bengal)', nativeName: 'कुड़मालि', flag: '🇮🇳', region: 'Asia' },
  { code: 'bpy-IN', name: 'Bishnupriya Manipuri (Assam & Tripura)', nativeName: 'বিষ্ণুপ্রিয়া মণিপুরী', flag: '🇮🇳', region: 'Asia' },
  { code: 'syl-BD', name: 'Sylheti (Bangladesh & India)', nativeName: 'ছিলটী / ꠍꠤꠟꠐꠤ', flag: '🇧🇩', region: 'Asia' },
  { code: 'ctg-BD', name: 'Chittagonian (Chittagong / Bangladesh)', nativeName: 'চাঁটগাঁইয়া', flag: '🇧🇩', region: 'Asia' },
  { code: 'ccp-BD', name: 'Chakma (Bangladesh & India)', nativeName: '𑄌𑄋𑄴𑄟𑄳𑄦 / Changma', flag: '🇧🇩', region: 'Asia' },
  { code: 'haj-IN', name: 'Hajong (Meghalaya & Assam / India)', nativeName: 'হাজং / Hajong', flag: '🇮🇳', region: 'Asia' },
  { code: 'kha-IN', name: 'Khasi (Meghalaya / India)', nativeName: 'Ka Ktien Khasi', flag: '🇮🇳', region: 'Asia' },
  { code: 'grt-IN', name: 'Garo / A\'chik (Meghalaya / India)', nativeName: 'A·chikku', flag: '🇮🇳', region: 'Asia' },
  { code: 'lus-IN', name: 'Mizo / Lushai (Mizoram / India)', nativeName: 'Mizo ṭawng', flag: '🇮🇳', region: 'Asia' },
  { code: 'trp-IN', name: 'Kokborok / Tripuri (Tripura / India)', nativeName: 'Kokborok', flag: '🇮🇳', region: 'Asia' },
  { code: 'njz-IN', name: 'Ao Naga (Nagaland / India)', nativeName: 'Ao O', flag: '🇮🇳', region: 'Asia' },
  { code: 'njm-IN', name: 'Angami Naga (Nagaland / India)', nativeName: 'Tenyidie', flag: '🇮🇳', region: 'Asia' },
  { code: 'nsm-IN', name: 'Sema / Sumi Naga (Nagaland / India)', nativeName: 'Sütsa', flag: '🇮🇳', region: 'Asia' },
  { code: 'lot-IN', name: 'Lotha Naga (Nagaland / India)', nativeName: 'Kyong', flag: '🇮🇳', region: 'Asia' },
  { code: 'nbe-IN', name: 'Konyak Naga (Nagaland / India)', nativeName: 'Konyak', flag: '🇮🇳', region: 'Asia' },
  { code: 'lep-IN', name: 'Lepcha (Sikkim / India & Nepal)', nativeName: 'Róng / ᰛᰩᰵ', flag: '🇮🇳', region: 'Asia' },
  { code: 'lif-NP', name: 'Limbu (Nepal & Sikkim / India)', nativeName: 'Sirijanga / ᤕᤠᤰᤌᤢᤱ ᤐᤠᤴ', flag: '🇳🇵', region: 'Asia' },
  { code: 'rab-NP', name: 'Rai / Bantawa (Nepal)', nativeName: 'बान्तवा', flag: '🇳🇵', region: 'Asia' },
  { code: 'taj-NP', name: 'Tamang (Nepal)', nativeName: 'तामाङ', flag: '🇳🇵', region: 'Asia' },
  { code: 'gvr-NP', name: 'Gurung (Nepal)', nativeName: 'तमु क्यी', flag: '🇳🇵', region: 'Asia' },
  { code: 'mgp-NP', name: 'Magar (Nepal)', nativeName: 'मगर ढूट', flag: '🇳🇵', region: 'Asia' },
  { code: 'new-NP', name: 'Newar / Nepal Bhasa (Kathmandu / Nepal)', nativeName: 'नेपाल भाषा', flag: '🇳🇵', region: 'Asia' },
  { code: 'xsr-NP', name: 'Sherpa (Nepal & Tibet)', nativeName: 'ཤར་པའི་སྐད / Sherpa', flag: '🇳🇵', region: 'Asia' },
  { code: 'thl-NP', name: 'Tharu (Terai / Nepal & India)', nativeName: 'थारू', flag: '🇳🇵', region: 'Asia' },
  { code: 'bft-PK', name: 'Balti (Gilgit-Baltistan / Pakistan)', nativeName: 'بلتی / སྦལ་ཏིའི་སྐད', flag: '🇵🇰', region: 'Asia', rtl: true },
  { code: 'lbj-IN', name: 'Ladakhi / Bhoti (Ladakh / India)', nativeName: 'ལ་དྭགས་སྐད་', flag: '🇮🇳', region: 'Asia' },
  { code: 'scl-PK', name: 'Shina (Gilgit / Pakistan & India)', nativeName: 'شینا', flag: '🇵🇰', region: 'Asia', rtl: true },
  { code: 'bsk-PK', name: 'Burushaski (Hunza / Pakistan)', nativeName: 'بروشسکی', flag: '🇵🇰', region: 'Asia', rtl: true },
  { code: 'khw-PK', name: 'Khowar / Chitrali (Chitral / Pakistan)', nativeName: 'کھوار', flag: '🇵🇰', region: 'Asia', rtl: true },
  { code: 'wbl-PK', name: 'Wakhi (Pamir / Pakistan & Tajikistan)', nativeName: 'خیک زبان / وخی', flag: '🇵🇰', region: 'Asia', rtl: true },
  { code: 'kls-PK', name: 'Kalasha (Chitral / Pakistan)', nativeName: 'Kalashamon', flag: '🇵🇰', region: 'Asia' },

  // Southeast Asian Mainland & Highland Tongues
  { code: 'kac-MM', name: 'Kachin / Jingpho (Kachin / Myanmar)', nativeName: 'Jinghpaw', flag: '🇲🇲', region: 'Asia' },
  { code: 'cnh-MM', name: 'Hakha Chin (Chin / Myanmar)', nativeName: 'Lai holh', flag: '🇲🇲', region: 'Asia' },
  { code: 'rki-MM', name: 'Rakhine / Arakanese (Rakhine / Myanmar)', nativeName: 'ရခိုင်စကား', flag: '🇲🇲', region: 'Asia' },
  { code: 'wba-MM', name: 'Wa (Shan State / Myanmar & China)', nativeName: 'Vax / 佤语', flag: '🇲🇲', region: 'Asia' },
  { code: 'blt-VN', name: 'Tai Dam / Black Tai (Vietnam & Laos)', nativeName: 'ꪼꪕꪒꪾ / Tay Dam', flag: '🇻🇳', region: 'Asia' },
  { code: 'twh-VN', name: 'Tai Dón / White Tai (Vietnam)', nativeName: 'Tay Dón', flag: '🇻🇳', region: 'Asia' },
  { code: 'khb-CN', name: 'Tai Lue / Dai (Xishuangbanna / China)', nativeName: 'ᦅᧄᦺᦑᦟᦹᧉ', flag: '🇨🇳', region: 'Asia' },
  { code: 'nod-TH', name: 'Northern Thai / Lanna / Kham Mueang (Thailand)', nativeName: 'คำเมือง / ᨣᩴᩤᨾᩮᩥᩬᨦ', flag: '🇹🇭', region: 'Asia' },
  { code: 'tts-TH', name: 'Isan / Northeastern Thai (Isan / Thailand)', nativeName: 'ภาษาอีสาน / ภาษาลาวอีสาน', flag: '🇹🇭', region: 'Asia' },
  { code: 'sou-TH', name: 'Southern Thai / Pak Tai (Southern Thailand)', nativeName: 'ภาษาไทยถิ่นใต้ / แหลงใต้', flag: '🇹🇭', region: 'Asia' },
  { code: 'cjm-VN', name: 'Eastern Cham (Vietnam)', nativeName: 'ꨌꩌ / Cham', flag: '🇻🇳', region: 'Asia' },
  { code: 'cja-KH', name: 'Western Cham (Cambodia)', nativeName: 'Uráng Cham', flag: '🇰🇭', region: 'Asia' },
  { code: 'jra-VN', name: 'Jarai (Central Highlands / Vietnam)', nativeName: 'Jörai', flag: '🇻🇳', region: 'Asia' },
  { code: 'rad-VN', name: 'Rade / Ede (Central Highlands / Vietnam)', nativeName: 'Klekei Êđê', flag: '🇻🇳', region: 'Asia' },
  { code: 'bdq-VN', name: 'Bahnar (Central Highlands / Vietnam)', nativeName: 'Bana', flag: '🇻🇳', region: 'Asia' },
  { code: 'sed-VN', name: 'Sedang (Central Highlands / Vietnam)', nativeName: 'Xơ Đăng', flag: '🇻🇳', region: 'Asia' },
  { code: 'kpm-VN', name: 'Koho (Lam Dong / Vietnam)', nativeName: 'Cơ Ho', flag: '🇻🇳', region: 'Asia' },
  { code: 'kdt-KH', name: 'Kuy / Kuay (Cambodia & Thailand)', nativeName: 'ภาษากูย / Kui', flag: '🇰🇭', region: 'Asia' },

  // Maritime Southeast Asian Tongues (Indonesia & Philippines & Malaysia)
  { code: 'sas-ID', name: 'Sasak (Lombok / Indonesia)', nativeName: 'Basa Sasak', flag: '🇮🇩', region: 'Asia' },
  { code: 'smw-ID', name: 'Sumbawa (Sumbawa / Indonesia)', nativeName: 'Basa Samawa', flag: '🇮🇩', region: 'Asia' },
  { code: 'bmq-ID', name: 'Bima / Mbojo (Sumbawa / Indonesia)', nativeName: 'Nggahi Mbojo', flag: '🇮🇩', region: 'Asia' },
  { code: 'mdr-ID', name: 'Mandar (West Sulawesi / Indonesia)', nativeName: 'Basa Mandar', flag: '🇮🇩', region: 'Asia' },
  { code: 'sda-ID', name: 'Toraja-Sa\'dan (South Sulawesi / Indonesia)', nativeName: 'Basa Tae\' Sa\'dan', flag: '🇮🇩', region: 'Asia' },
  { code: 'mrg-ID', name: 'Manggarai (Flores / Indonesia)', nativeName: 'Tombo Manggarai', flag: '🇮🇩', region: 'Asia' },
  { code: 'bew-ID', name: 'Betawi (Jakarta / Indonesia)', nativeName: 'Basa Betawi', flag: '🇮🇩', region: 'Asia' },
  { code: 'mfa-TH', name: 'Pattani Malay / Yawi (Southern Thailand)', nativeName: 'Bahasa Melayu Patani / بهاس ملايو ڤتانى', flag: '🇹🇭', region: 'Asia', rtl: true },
  { code: 'zlm-MY', name: 'Kelantan Malay (Kelantan / Malaysia)', nativeName: 'Baso Kelate', flag: '🇲🇾', region: 'Asia' },
  { code: 'meo-MY', name: 'Kedah Malay (Kedah / Malaysia)', nativeName: 'Pelat Utagha / Bahasa Melayu Kedah', flag: '🇲🇾', region: 'Asia' },
  { code: 'tgl-US', name: 'Tagalog (United States diaspora)', nativeName: 'Tagalog (US)', flag: '🇺🇸', region: 'Americas' },
  { code: 'iba-MY', name: 'Iban (Sarawak / Malaysia & Borneo)', nativeName: 'Jaku Iban', flag: '🇲🇾', region: 'Asia' },
  { code: 'dtp-MY', name: 'Kadazan-Dusun (Sabah / Malaysia)', nativeName: 'Boros Dusun / Kadazan', flag: '🇲🇾', region: 'Asia' },
  { code: 'bjn-MY', name: 'Banjar (Malaysia & Indonesia)', nativeName: 'Bahasa Banjar', flag: '🇲🇾', region: 'Asia' },
  { code: 'tsg-PH', name: 'Tausug (Sulu / Philippines & Malaysia)', nativeName: 'Bahasa Sūg', flag: '🇵🇭', region: 'Asia' },
  { code: 'mdh-PH', name: 'Maguindanao (Mindanao / Philippines)', nativeName: 'Basalo Magindanaw', flag: '🇵🇭', region: 'Asia' },
  { code: 'mrw-PH', name: 'Maranaw (Mindanao / Philippines)', nativeName: 'Mëranaw', flag: '🇵🇭', region: 'Asia' },
  { code: 'yka-PH', name: 'Yakan (Basilan / Philippines)', nativeName: 'Bahasa Yakan', flag: '🇵🇭', region: 'Asia' },
  { code: 'krx-PH', name: 'Kinaray-a (Panay / Philippines)', nativeName: 'Kinaray-a', flag: '🇵🇭', region: 'Asia' },
  { code: 'cps-PH', name: 'Capiznon (Capiz / Philippines)', nativeName: 'Capiceño', flag: '🇵🇭', region: 'Asia' },
  { code: 'sur-PH', name: 'Surigaonon (Mindanao / Philippines)', nativeName: 'Jaun-jaun Surigaonon', flag: '🇵🇭', region: 'Asia' },
  { code: 'ivv-PH', name: 'Ivatan (Batanes / Philippines)', nativeName: 'Chirin nu Ibatan', flag: '🇵🇭', region: 'Asia' },

  // Eastern Indonesian & Papuan Tongues
  { code: 'mqy-ID', name: 'Manggarai (West Flores / Indonesia)', nativeName: 'Manggarai', flag: '🇮🇩', region: 'Asia' },
  { code: 'tet-ID', name: 'Tetun Terik (West Timor / Indonesia)', nativeName: 'Tetun Terik', flag: '🇮🇩', region: 'Asia' },
  { code: 'uab-ID', name: 'Uab Meto / Dawan (West Timor / Indonesia)', nativeName: 'Uab Meto', flag: '🇮🇩', region: 'Asia' },
  { code: 'gal-ID', name: 'Galela (Halmahera / Indonesia)', nativeName: 'Basa Galela', flag: '🇮🇩', region: 'Asia' },
  { code: 'tbf-ID', name: 'Tobelo (Halmahera / Indonesia)', nativeName: 'Basa Tobelo', flag: '🇮🇩', region: 'Asia' },
  { code: 'ttr-ID', name: 'Ternate (North Maluku / Indonesia)', nativeName: 'Basa Ternate', flag: '🇮🇩', region: 'Asia' },
  { code: 'tid-ID', name: 'Tidore (North Maluku / Indonesia)', nativeName: 'Basa Tidore', flag: '🇮🇩', region: 'Asia' },
  { code: 'amb-ID', name: 'Ambonese Malay (Ambon / Maluku)', nativeName: 'Bahasa Ambon', flag: '🇮🇩', region: 'Asia' },
  { code: 'kei-ID', name: 'Kei / Evav (Kei Islands / Maluku)', nativeName: 'Veveu Evav', flag: '🇮🇩', region: 'Asia' },
  { code: 'bhw-ID', name: 'Biak (Papua / Indonesia)', nativeName: 'Wos Biak', flag: '🇮🇩', region: 'Asia' },
  { code: 'dni-ID', name: 'Dani (Baliem Valley / Papua / Indonesia)', nativeName: 'Dani', flag: '🇮🇩', region: 'Asia' },
  { code: 'ekg-ID', name: 'Ekari / Mee (Papua / Indonesia)', nativeName: 'Mee Mana', flag: '🇮🇩', region: 'Asia' },
  { code: 'asg-ID', name: 'Asmat (Papua / Indonesia)', nativeName: 'Asmat', flag: '🇮🇩', region: 'Asia' },
  { code: 'mrh-ID', name: 'Marind (Merauke / Papua / Indonesia)', nativeName: 'Marind', flag: '🇮🇩', region: 'Asia' },
  { code: 'snt-ID', name: 'Sentani (Lake Sentani / Papua)', nativeName: 'Sentani', flag: '🇮🇩', region: 'Asia' },
];

